### ISSUE TITLE
Active Groups: change text color and cursor type

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#1000]
Agent View page shows a section called Active Groups which is currently using a different color for their text/links than the one used on the UI Spec.

![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/3e6f82a8-fab9-477a-ab34-2f135827537e)

Also, when we hover over the group names links, the cursor should be changed according (pointer cursor)

**Comment by manrodrigues** [comment]
The color is still different. For elements we expect a bold white string. Green is used to describe the session. 

![image](https://user-images.githubusercontent.com/78241475/161065750-8997dc43-79cb-4dd1-9997-c957c66c8509.png)


Cursor is ok:

![cursor_ok](https://user-images.githubusercontent.com/78241475/161065490-b9594e81-1ce9-4190-84a8-4d46f2d4e764.gif)

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/162351939-4ac3defe-7384-40c8-ae41-7066f18dbb34.png)
