### ISSUE TITLE
Policy error message missing on Agent View Page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#1001]
As shown on the UI Spec, in the Active Policies/Datasets section we must show an error message if the policy failed to be applied or if the service response came with the error property message filled.

![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/04c60a0e-c5d5-42ac-8ba8-c0a5e56ca820)

**Comment by gpazuch** [comment]
@iatdaitan @dscabral 
https://github.com/ns1labs/orb/wiki/Architecture:-Policies-and-Datasets
https://github.com/ns1labs/orb/wiki/Architecture:-Fleet
https://getorb.io/api/policies.html#operation/readPolicy

Can you update wiki/docs and link it here to the specification of the possible policy states?

```
{
  "id": "f1b0b3ff-f069-44d5-9620-5be2ce35e333",
  "name": "test_agent_01",
  "state": "online",
  "channel_id": "40ba041c-1e4d-4c61-9f5d-7acfa40ab148",
  "agent_tags": { },
  "orb_tags": {
    "run": "true",
    "test": "true"
  },
  "agent_metadata": {
    "backends": {
      "pktvisor": {
        "data": {
          "taps": {
            "default_pcap": {
              "config": {
                "iface": "enp0s31f6"
              },
              "input_type": "pcap",
              "interface": "visor.module.input/1.0"
            }
          }
        },
        "version": "4.1.0-develop-7aad517"
      }
    },
    "orb_agent": {
      "version": "0.13.0-develop"
    }
  },
  "last_hb_data": {
    "backend_state": {
      "pktvisor": {
        "state": "running"
      }
    },
    "group_state": {
      "ea55360f-21f9-451d-af3e-aa9811096e8f": {
        "channel": "c5dea671-4a60-4469-ac09-85717c94aba7",
        "name": "test_group_01"
      }
    },
    "policy_state": {
      "a32cb54b-a7f8-4aee-a43b-c5ee4a888f1b": {
        "datasets": [
          "5d6820ec-c690-498e-bf62-e8a66e16e1e9"
        ],
        "name": "test_policy_01",
        "state": "running"
      },
      "bde6fbb1-ba79-454d-ab7f-c3d05dc3bdd9": {
        "datasets": [
          "4b215673-7e88-4bcd-bce3-bbd495772f9b"
        ],
        "error": "500 missing or invalid policy kind at key 'kind'",
        "name": "test_policy_02",
        "state": "failed_to_apply"
      }
    }
  },
  "ts_created": "2022-03-28T14:37:20.566293Z",
  "ts_last_hb": "2022-03-28T18:35:22.619786Z"
}
```

Some structures as getting a bit confusing, because they offer diferent views of a same entity, sometimes paired to other entities that are not available via other routes.

Would it be possible to refactor these services' models to be a bit more concise and consider adopting a unique view of a model throughout the services?

**Comment by gpazuch** [comment]
@dscabral @iatdaitan 
One other thing
keep the separators on the message as '-' instead of '_'
like the other statuses.
'failed_to_apply'

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/160472829-a6721d13-f88a-4069-a036-4379be203891.png)

**Comment by manrodrigues** [comment]
ok

last commit: https://github.com/ns1labs/orb/commit/3a80dfce9e824daea58ff483d1cc85867dcd4a34

![image](https://user-images.githubusercontent.com/78241475/160939410-f7bfa927-3768-46ed-90e6-6c1acd3aa1be.png)
