### ISSUE TITLE
Remove agent group from dataset db when group is deleted

### ISSUE THREAD

**Issue by mclcavalcante** [ns1labs/orb#1005]
After deleting an agent group that is linked to a dataset, the dataset became invalid but the group is still part of it. Which breaks the dataset view. The group should also be removed from DB
![dsView.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/fee6f19d-d856-46f0-a35c-06b359d28b8f)
![dsList.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/3349432a-d347-4219-8028-ea60461c5ff7)
![groupDeleted.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/e6f82e7b-13c8-447c-86cc-a3fbe2382626)
![image.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/e4e7b875-a2a9-4fa6-817b-9d940e49822f)

**Comment by lpegoraro** [comment]
@manrodrigues did brought some unexpected scenarios?

**Comment by manrodrigues** [comment]
Related with #1104

**Comment by lpegoraro** [comment]
the extra scenario is related to #1104 so this is closed
