### ISSUE TITLE
Remove policy from dataset db when policy is deleted

### ISSUE THREAD

**Issue by mclcavalcante** [ns1labs/orb#1007]
After deleting a policy that is linked to a dataset, the dataset became invalid but the policy is still part of it. Which breaks the dataset view. The policy should also be removed from DB
![image.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/df15ddf9-75ec-48f9-8bb0-e09b79c439e9)
![image.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/41754935-4b32-4566-9898-12f9ff3118b0)
![image.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/4b7c4df9-8799-47b6-b619-4a4a1e88d12b)
![image.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/cc693cb6-c002-4c72-a2fd-271151749ea9)
![image.png](https://images.zenhubusercontent.com/619410c7e9ff4fd10ac8324e/b1e37b50-de17-443f-93eb-a74238a518cc)

**Comment by lpegoraro** [comment]
The unexpected scenario will be handled by #1104
