### ISSUE TITLE
Policies: "Next" button on first page of policy creation must be on left side

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1014]
To maintain the pattern and guarantee tab control the "next" button must be on left side and must be the first option of tab after description.

Just the first page need to be corrected

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/33ae2bef-6120-49b9-8bd4-f2923815ddf6)

**Comment by brunofariasdeo** [comment]
Hi @manrodrigues ,

This issue is no longer reproducible in Policies:
![image](https://user-images.githubusercontent.com/42921279/178767183-58a1d883-8cbd-452c-a38b-cc5eecac413b.png)

I believe that it was resolved in [#638](https://github.com/ns1labs/orb/issues/638)

**Comment by manrodrigues** [comment]
ok
