### ISSUE TITLE
Policies: Wrong message for editing process of policies create through yaml config

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1019]
When a policy is created through yaml option, when try to edit the policy, the UI informs that there is no agents available, what is not correct.

Steps to reproduce:

1 - Create and provision an agent
2 - Create a policy using yaml option
3 - Try to edit the policy

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/24be64fb-6624-4ebe-9851-c0b6857eb35b)

**Comment by gpazuch** [comment]
@manrodrigues is this still happening?

**Comment by manrodrigues** [comment]
No. That's ok!

![policy_editing](https://user-images.githubusercontent.com/78241475/171696227-7448244f-0cc1-4677-9fb0-ae3c4c76b8c9.gif)
