### ISSUE TITLE
Add sample policies after user registration

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#1037]
As a user, I would like to have sample policies in place right after my account has been created, making it easier to use it out of the box or create policies by myself.

--

TBD: Technical description
Note: 
- It would be good to have some examples of policies created using the Advanced option (YAML).
- Create a signup workflow to call needed APIs endpoint to create general settings like samples of policies.
- Later, we can enhance this workflow and create a fully featured general settings

**Comment by manrodrigues** [comment]
Closing based on:

#1056 #886 #513
