### ISSUE TITLE
Show # agents using a policy / dataset

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#1038]
As a user, I would like to see how many agents are running a specific policy and each one its datasets to have an idea of the policy extent.

--

Screenshot: TBD

Description: TBD

**Comment by manrodrigues** [comment]
We have it in each policy view:

![image](https://user-images.githubusercontent.com/78241475/180497974-6dcf1dd6-1501-4ff2-8f33-1e7113b282eb.png)
