### ISSUE TITLE
Datasets: use the name of missing element instead of the id

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1049]
when some element linked to a dataset is removed, the message show the id of the missing elemente, but the user never have access to the id, so the name should be used instead.

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/2aa3c448-52e1-407d-bc5a-3fcfb326532e)

**Comment by gpazuch** [comment]
@manrodrigues I cannot show the name of said object, since it is no longer available/retrievable - it has already been removed.

<closing this issue>
