### ISSUE TITLE
Removing a policy should remove all of its Datasets

### ISSUE THREAD

**Issue by mclcavalcante** [ns1labs/orb#1068]
Currently, we are allowed to remove a policy and leave datasets that used that policy (which then become invalid) visible on the dataset page. Once we move datasets into the policy page and remove the general Datasets screen, then removing a policy should probably remove all of its Datasets once they will not be able to reach them anymore, so they would be unusable.

**Comment by manrodrigues** [comment]
OK. Well done :)

![remove_policy_dataset](https://user-images.githubusercontent.com/78241475/178992550-e2ecd641-57b8-4fda-9abf-ba934461de41.gif)
