### ISSUE TITLE
Policies: NEXT button and form options must being dynamic configured when re-choose a tap option

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1091]
When more than one tap is available as options on policies creation, if user choose one and then re-choose another one, the "next" button and the form option must be dynamic configured. On current ORB, after choose pcap option, the UI maintain the configs for pcap policies and the "next" button remains enabled.

Steps to reproduce:
- Provision an agent with pcap tap
- Provision an agent with sflow tap
- On policies creation page, click on pcap option and then click on sflow option

Expected result:
- When sflow is choose, forms option and "next" button must be re-configured

Current result:
- Configs from pcap are being kept 

![sflow.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/84305a23-d064-410f-acba-d2211fc7ab2a)

**Comment by gpazuch** [comment]
blocked by #1089

**Comment by gpazuch** [comment]
wizard phased out #2090
