### ISSUE TITLE
Dataset Modal Changes

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1099]
Few of the changes to Dataset Modal discussed on last UI/UX meeting

* name field should be last in form

* policy selector should not appear when creating dataset from policy view.

* group selector should not appear when creating dataset from agent group view(does not exist as of yet)

**Comment by manrodrigues** [comment]
- name field should be last in form -> ok

- policy selector should not appear when creating dataset from policy view. -> ok

![image](https://user-images.githubusercontent.com/78241475/164598489-36f4d529-2db0-48b5-9347-fc466e54668f.png)

![image](https://user-images.githubusercontent.com/78241475/164598626-3be1692f-6263-4b17-9be7-47e012b56d77.png)

@gpazuch on dataset details we should dispay the policy? and if yes, "collection policy" is the right name for this field?
