### ISSUE TITLE
Agents: after remove a group from orb, agent is not unsubscribed from this groups

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1104]
``` {"level":"info","ts":1650643667.2475095,"caller":"agent/comms.go:72","msg":"completed RPC unsubscription to group","topic":"channels/8d4273fa-16c3-4dcc-88f5-904f545f8b5d/messages/fromcore"} ```

Although the agent logs inform that the agent was unsubscribed, on backend side the  group was not unlinked to the agent and, so, the policies and dataset keeps attached on agent's heartbeat.

Steps to reproduce:

- Create and provision an agent
- Create a group that matches this agent
- Create a sink
- Created a policy
- Create a dataset linking the group created
- Check if the policy is running on agent's view page
- Remove the group from orb (delete it)
- Check the agent's view page and check if the groups, dataset and policies are unapplied to the agent

expected behavior:
- group, policies and dataset must be unnatached

Current behavior:
- groups, policies and datasets are not unapplied

**Comment by lpegoraro** [comment]
Need to check th heartbeat and remove from policy

**Comment by manrodrigues** [comment]
Ok. It's working!

Lets keep the time in mind, thought (https://github.com/ns1labs/orb/issues/1045)


![group_unsubscription](https://user-images.githubusercontent.com/78241475/176449487-5e58615c-96db-45fb-93ef-8f0c56c82bd3.gif)
