### ISSUE TITLE
Menu: sinks must be displayed above policies

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1107]
Considering the logic creation, the sink must be above the policy.. you have changed the order:

![image](https://user-images.githubusercontent.com/78241475/164607507-12f59f47-5eb4-4a26-a4ca-84c7d7fec1dd.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/164776326-56cc9b51-4d16-4870-833e-24127c3aa55d.png)

https://www.figma.com/file/5jZNpc8JMsY2Tj3OQJzgxt/Orb-Product-Portal-UI?node-id=1585%3A6034

According to the screenshot found on figma on last updates/discussion.

<Closing this issue>
