### ISSUE TITLE
Policies view: when policy with datasets is removed from orb, the dataset is not removed from backend

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1119]
When a policy with dataset is removed from orb, the deletion of datasets linked IS NOT working at all.. although the dataset is being removed from policies view page, the dataset remains existing on backend and on dataset route. Considering that this route was not suppose to exist anymore, we will have a lot of datasets polluting our databases.

Check:

![dataset_not_removed](https://user-images.githubusercontent.com/78241475/164729693-4203c9b9-4a5b-4723-990b-1ec54df806f2.gif)

**Comment by gpazuch** [comment]
@manrodrigues is Orb UI failing to call the remote endpoint for policy OR dataset delete?

**Comment by manrodrigues** [comment]
@gpazuch not, sorry. I insert the wrong tag here.

**Comment by manrodrigues** [comment]
Closing based on #1068
