### ISSUE TITLE
Agent groups: poorly distribution of last activity on agent matching expanded table

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1129]
Steps to reproduce:

- Starts to create a new agent group
- Insert a tag that matches with some agent
- Expand the view of agent that matches
- Back to the tag page
- Remove the tag and add again (same one or another one that matches with some agent as well)
- Move to next page

Expected result:

- the data in the table must be well distributed
Current result:

- Last activity is not well distributed

Check:

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/52aa2b1f-b07f-408b-8401-453048dae0eb)

Using smaller screen:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/a5d300f8-bc56-4fc8-bc50-0192db574b7f)

**Comment by brunofariasdeo** [comment]
@manrodrigues ,
this issue is no longer reproducible

https://user-images.githubusercontent.com/42921279/181041047-fc2c0b15-6a5c-4ffd-91e3-2081f8f9604c.mp4
