### ISSUE TITLE
Policies: After finishing the creation of a policy, the user must be directed to this policy's view page

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1135]
Considering the new way to create a dataset, when the user finishes to create a policy, he must be directed to this policy's view page (instead of to the all policies list). It will make the process to create a dataset more intuitive to the users.

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/170546959-b748ca23-1749-4cfe-9c8f-fcac5f13b26e.png)

**Comment by manrodrigues** [comment]
Good! ok 

![policy_redirecting](https://user-images.githubusercontent.com/78241475/171665604-1a2caa07-11cb-4faf-936e-ca9cc3286b7f.gif)
