### ISSUE TITLE
Sink Management: Unable to create sink using only required fields

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#117]
Steps to reproduce:

- open ORB on Sink Management page
- Press "+NEW SINK"
- Choose Sink Type
- Press "Next"
- Insert a Remote Host

Expected Result:

"NEXT" button should be available

Current Result:

"NEXT" button is not available

Check the issue by clicking here: https://drive.google.com/file/d/1qGdLsMKpUwZcj-0tuN-2ltrSjC5ZNqSj/view?usp=sharing

**Comment by iatdaitan** [comment]
CLOSING:

Working as expected. All fields except Sink Description are required. Figma must be updated to match this business rule.
