### ISSUE TITLE
Change GROUP(1) to group (1/1)

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1173]
On Dataset View Page - 

Change `GROUP(1)` to `group (1/1)`
Update via CSS 
Check if the `1 agent online out n` values to be correct.

**Comment by manrodrigues** [comment]
The notation is ok, but we missed the explanation like `1 agent online out n`. Please, check.

![image](https://user-images.githubusercontent.com/78241475/170174264-efb881a4-9a31-4e06-89a5-b4b22a8ee13c.png)

**Comment by manrodrigues** [comment]
Now its fully ok :) 

![group_description](https://user-images.githubusercontent.com/78241475/171666684-51d7c988-51f2-4336-967c-d9640af07ecd.gif)


![image](https://user-images.githubusercontent.com/78241475/171667024-c0d80494-89ca-42f2-b984-4adda35af356.png)
