### ISSUE TITLE
Delete Policy Modal - adjustments

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1175]
Add the policy name as text in the message
Add text to button "I understand remove the policy and all datasets

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/168653991-73a01484-daed-4ebb-bd07-029be24d29e6.png)

**Comment by manrodrigues** [comment]
LGTM

![image](https://user-images.githubusercontent.com/78241475/169538865-79317575-d3ae-44d4-9844-cb4c7a137ed3.png)
