### ISSUE TITLE
add agent tags as metric labels to sinker parser

### ISSUE THREAD

**Issue by mclcavalcante** [ns1labs/orb#1199]
Sinker must be able to get agent tags attached to an agent and parse these tags as labels in Prometheus format while scraping metrics. 
example: 

- Prometheus format:

```
# HELP base_event_rate Rate of events
# TYPE base_event_rate summary
base_event_rate{module="default-db671776ba70b178-resources",policy="default-db671776ba70b178-resources",pop="eu3p2",quantile="0.5",region="EU"} 0
base_event_rate{module="default-db671776ba70b178-resources",policy="default-db671776ba70b178-resources",pop="eu3p2",quantile="0.9",region="EU"} 1
```

**Comment by leoparente** [comment]
@mclcavalcante  @lpegoraro  We should do that change on orb-agent. it would use the 'agent_tags' and add it by default to prometheus format while scrapping metrics to sinker

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/171931567-fd0d13fe-1418-4970-9a9f-ae54519a2bcd.png)

![image](https://user-images.githubusercontent.com/78241475/171931793-334fc14c-48fc-4838-ad1d-bb97bbf22cef.png)
