### ISSUE TITLE
speed up buildx compilation for pktvisor

### ISSUE THREAD

**Issue by etaques** [ns1labs/orb#1206]
speed up buildx compilation for pktvisor its taking 13 hours to finish. Add docker cache and optimize docker multi stage images to improve performance during image build.

**Comment by etaques** [comment]
Currently we was taking 13 hours to build docker images for all architectures needed.
Now it was reduced to 4 hours for arm64 and 4hours for armv7. 
Im still waiting to finish my tests to close this task.

**Comment by lpegoraro** [comment]
Status 
- [x] Build arm64
- [x] Build amd64
- [ ] Build arm32

**Comment by etaques** [comment]
amd64=15min
arm64=35min
arm32=4h

**Comment by etaques** [comment]
This is the flow, just waiting for the right token permissions to generate self hosted runners for github
![image.png](https://images.zenhubusercontent.com/621ce94d7492e430afadf14e/f0de20d1-f5ac-4ecd-8942-ec8a928c998f)
