### ISSUE TITLE
Purge channels in mqtt and remove entry when agent group is deleted in orb

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1219]
Check the MQTT channel if it is deleted when an agent is deleted, so the following scenario does not happen

## Testable Scenario 1

Given an agent with {agentID}  with  {agentID},  {channelID} and {channelKey}
When I delete the agent with the {agentID}
And I would try to connect to MQTT server with a separate client

### Expected 

Then the MQTT complains the channel does not exist

### Actual

The MQTT channel  connects

### Technical details

On the function, https://github.com/ns1labs/orb/blob/6354af162b336b4cfb5fc95cc3675662589583b8/fleet/agent_group_service.go#L227
needs to have this increment of code
```
        err := svc.mfsdk.DeleteChannel(groupId, token)
	if err != nil {
		return AgentGroup{}, errors.Wrap("error while deleting channel" , err)
	}
```

**Comment by manrodrigues** [comment]
channels have been removed


![image](https://user-images.githubusercontent.com/78241475/179002610-8d7d0af5-4f3a-4879-a6e8-c7499bea5375.png)

![image](https://user-images.githubusercontent.com/78241475/179003058-1f55915b-bc80-4ed1-8997-86ad7be2cc41.png)
