### ISSUE TITLE
Agents: provide a visual cue that there are more tags associated with an agent

### ISSUE THREAD

**Issue by rboucher-ns1** [ns1labs/orb#1239]
In the Agent List, when an Agent has too many Tags to display, they are simply not shown. The blank space to the right of the Tag list seems to indicate there are no additional tags, which isn't necessarily the case. Some visual cue should be provided to indicate there are more tags (but just not displayed in this view).
![Image 2022-05-24 at 10.18.07 AM.jpg](https://images.zenhubusercontent.com/6275686817eae782dc76eac9/2d2b4f8d-b07d-49b0-9371-b5c13f1913a5)
In the example above, the agents have more than the 3 tags shown:
![Image 2022-05-24 at 10.19.03 AM.jpg](https://images.zenhubusercontent.com/6275686817eae782dc76eac9/e573da95-c606-4e3f-b08a-25672f6deb01)
One possible solution would be to have the last tag displayed on the right be an ellipsis (...)

**Comment by manrodrigues** [comment]
I think it's ok. @rboucher-ns1 Do you want to comment?


![name_tags_displayed](https://user-images.githubusercontent.com/78241475/176453693-49ce61a2-601e-4357-809d-be097d83610c.gif)

**Comment by rboucher-ns1** [comment]
Yes, this is great! I don't think we need anything more for this.
