### ISSUE TITLE
Agents: tag "bubbles" should use consistent colors

### ISSUE THREAD

**Issue by rboucher-ns1** [ns1labs/orb#1240]
In the Agents List view, Tags are shown with a background color that is different from that shown in the Agent Details window. (The Agent View appears to show consistent colors with the Agent List)
![Image 2022-05-24 at 10.26.58 AM.jpg](https://images.zenhubusercontent.com/6275686817eae782dc76eac9/fc443989-62b0-47e0-82ee-90d8b192453f)
![Image 2022-05-24 at 10.27.44 AM.jpg](https://images.zenhubusercontent.com/6275686817eae782dc76eac9/c165d897-7c51-407b-a96e-0553a8b72dca)

**Comment by brunofariasdeo** [comment]
Hi @manrodrigues ,
This issue is no longer reproducible in master.
May I ask you to validate it?
Thanks!

**Comment by manrodrigues** [comment]
That's pk :)

![image](https://user-images.githubusercontent.com/78241475/178772289-4407036b-28b7-420a-b2b5-182d477b4651.png)

![image](https://user-images.githubusercontent.com/78241475/178772390-1202460d-6748-4aaf-8c89-b33e7912b173.png)

-----------

![image](https://user-images.githubusercontent.com/78241475/178772520-b6a59306-7e04-481b-88f4-254bf302606c.png)

![image](https://user-images.githubusercontent.com/78241475/178772619-086c9675-d270-40b2-8e93-00b056ec4743.png)

-----------

![image](https://user-images.githubusercontent.com/78241475/178772768-9ec64b91-ad69-4498-83e3-620d3ff0a2fd.png)
![image](https://user-images.githubusercontent.com/78241475/178772819-8dd00874-ef59-40e4-8af4-8f1ee6717c11.png)
