### ISSUE TITLE
Implement different styles to orb tags and agent tags

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1242]
As now we have unique tags on Orb UI (https://github.com/ns1labs/orb/pull/1235) and org tags are editable, but agent tags are not, we need to have a way to make easy to the user identify which tags come from agent (and can't be edited) and which one come from orb (and can be edited).

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/170593335-f55937ec-df9a-4c42-834b-815216298c39.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/170593524-2e78409d-a18b-48cb-8d1d-c163ddf67885.png)

**Comment by rboucher-ns1** [comment]
FWIW, I like the view with the Tags already split between "Agent Tags" and "Orb Tags". I'm not sure the SPLIT and UNIFY toggles are necessary.

That said, I would suggest we add a tooltip next to "Agent Tags" and "Orb Tags" to make the difference clear:

Agent Tags tooltip: "These tags were configured in the agent and were inherited into Orb" 
Orb Tags tooltip: "These tags were configured in Orb and propagated to the agent"

**Comment by manrodrigues** [comment]
Very good :) 

![image](https://user-images.githubusercontent.com/78241475/171894248-f708b003-d6ca-48b6-8bfd-b9af646df8a2.png)
