### ISSUE TITLE
Agents view: Change message for "new" agents using "New. This Agent has been provisioned but never connected."

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1278]
When an agent is in new status agent view page is displaying: "New. This Agent has not been provisioned." .... it should actually say: 
`"New. This Agent has been provisioned but never connected."`

![Untitled presentation (3).jpg](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/c894908e-7324-4960-bf2d-59705acdc983)

**Comment by gpazuch** [comment]
@manrodrigues @rboucher-ns1 

see https://github.com/ns1labs/orb/pull/1279

and

https://github.com/ns1labs/orb/issues/1280
