### ISSUE TITLE
Status Filter is not intuitive

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1284]
To filter a list of Orb Entities where `status` property is present **demands** the user to know the possible **Status** an entity may present itself.

`status` values should be available to the user to select from as a dropdown.

![image](https://user-images.githubusercontent.com/1490938/171723686-a2eecb91-78c7-4c97-9c95-5b192ed4d76f.png)

https://github.com/ns1labs/orb/wiki/Architecture:-Policies-and-Datasets#dataset-data-model
dataset valid: 'true' | 'false'

https://github.com/ns1labs/orb/wiki/Architecture:-Fleet#agent-data-model
agent state: 'new' | 'online' | 'offline' | 'stale' | 'removed'

https://github.com/ns1labs/orb/wiki/Architecture:-Sinks
sink state: 'error' | 'active'

**Comment by gpazuch** [comment]
note: `state` prop is being represented as `Status`

**Comment by manrodrigues** [comment]
Ok for the lists.. i'll open a new card to the things listed below: 

- The "removed" state is not expected to be listed

![image](https://user-images.githubusercontent.com/78241475/179043512-f70d897f-fb51-42f1-9896-c07899fc0959.png)

- "Unknown" status is missing

![image](https://user-images.githubusercontent.com/78241475/179043646-b20762db-4b00-4614-aeca-202e052d7aae.png)
