### ISSUE TITLE
Multiple Filter Search Tool

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1285]
Search Tool only allows filtering by one property, requires too much effort to sift through large amounts of rows/data.

It is impossible to join filters

> e.g. status='online' && tags={...}  

![image](https://user-images.githubusercontent.com/1490938/171741628-0d85d6c0-c8d0-48e6-aa05-6196b6d36ca5.png)

---
perhaps initially show input fields for all properties that can be filtered

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/171742814-06f17d56-35ac-4569-b89e-1904c8426227.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/177338029-17e94f46-015f-45fc-bb52-8ae27f9c8a3d.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/177338794-8ad27d8f-7fcb-4a42-bf73-86fa102c15a4.png)
![image](https://user-images.githubusercontent.com/1490938/177338891-58b2ce0a-2edc-477d-b8aa-43021042c1c8.png)
![image](https://user-images.githubusercontent.com/1490938/177339087-22437a2d-ef15-42ff-9c56-a24f91676e39.png)
![image](https://user-images.githubusercontent.com/1490938/177339204-63a6c11a-f897-4c70-a9c5-d72f9ae7709c.png)
![image](https://user-images.githubusercontent.com/1490938/177339239-8fec5552-cccb-42ff-9283-1d23d1fcb864.png)

Filter Tool is implemented and ready to be imported to orb.

Still missing is the exact match vs partial match on input types

**Comment by manrodrigues** [comment]
ok

![filter_working](https://user-images.githubusercontent.com/78241475/179042263-92170045-b6d6-4df6-9810-6750fa56503a.gif)
