### ISSUE TITLE
Change Input for Agent Group Selector on Dataset Create/Edit

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1287]
It is too much work to scroll through hundreds of agents.

Implement input with text suggestion and possibly dropdown as well.

![image](https://user-images.githubusercontent.com/1490938/171745550-46dd35db-f8b1-49f7-9913-1f7546d47e03.png)

**Comment by manrodrigues** [comment]
The filter is working. but if the user chose the group using the list, modal fail to identify the group and save button is not enabled.

![failing_to_recognize_group](https://user-images.githubusercontent.com/78241475/173628170-335c339a-83d7-403d-aee0-8142b5520041.gif)

**Comment by manrodrigues** [comment]
This is very good. Nice job! :)

![group_selector](https://user-images.githubusercontent.com/78241475/176451654-821b6569-ffe6-4106-817f-30758b02a584.gif)
