### ISSUE TITLE
Sink Select '+' sign action

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1288]
Sink Add <'+' button> is easy to miss and also becomes repetitive.

Add sink on select action. User can remove sink if sink is added by mistake.

Remove '+' button.

![image](https://user-images.githubusercontent.com/1490938/171745767-9fcc0366-5ceb-4a8e-b9a3-6f44822101cc.png)

**Comment by gpazuch** [comment]
@rboucher-ns1 should we consider the same case as group dropdown selector? Perhaps autosuggestion with text input field and <ENTER> action could do better for these too.

**Comment by manrodrigues** [comment]
After add second sink the "sink name" field keeps with one sink name.. we need to keep the field as "sink name" on the box

![sink](https://user-images.githubusercontent.com/78241475/174862947-8062d467-7a6f-48b0-8384-d3d65a566a49.gif)

(I will put it in other issue)
