### ISSUE TITLE
Policies: boxes on policy creation page have inconsistent size

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1308]
The size of the boxes on the policy creation page is inconsistent

![policies_box_size.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/b2dc6172-b4ce-4a1f-bdd6-7f7a072e6085)

**Comment by manrodrigues** [comment]
Note: this is happening for all orb pages

**Comment by gpazuch** [comment]
Could you confirm this is still happening after https://github.com/ns1labs/orb/pull/1384 ?

**Comment by manrodrigues** [comment]
I guess it's ok now :) 

![policy_box](https://user-images.githubusercontent.com/78241475/176454501-99d806e9-fb46-4773-b884-77d06e17553d.gif)
