### ISSUE TITLE
Control plane needs to delete wrong policy if it was changed

### ISSUE THREAD

**Issue by etaques** [ns1labs/orb#1342]
The problem description is on this link (slack channel)
https://ns1labs.slack.com/archives/C01UNG6UK37/p1655333496644379

Brief problem description :
if pktvisor was requested to delete any policy and pktvisor api returns 404, policy needs to be removed from fleet, because is not applied on pktvisor.

![image.png](https://images.zenhubusercontent.com/621ce94d7492e430afadf14e/974cd66e-0526-4e75-b107-dd01649ea79d)

**Comment by manrodrigues** [comment]
[_affectionate_jones_logs.txt](https://github.com/ns1labs/orb/files/9444640/_affectionate_jones_logs.txt)

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/194641311-0a378dba-9f1f-44f0-8374-398639cf0f27.png)
