### ISSUE TITLE
Metrics from undefined Handlers being pushed to Prometheus Sink

### ISSUE THREAD

**Issue by rboucher-ns1** [ns1labs/orb#1398]
Please look into why metrics from undefined Handlers (i.e. handlers not defined in the agent policy) are showing up in the Prometheus database. To start the investigation, we need to determine:

- Are the unwanted metrics included in the JSON coming from the pktvisor agent?
- Are the unwanted metrics being synthesized by the sinker prior to be being sent to Prometheus?

**Comment by rboucher-ns1** [comment]
The agents I observed this on were running this simple policy:
```{
  "handlers": {
    "modules": {
      "handler_dns_1": {
        "filter": {},
        "type": "dns"
      },
      "handler_net_1": {
        "type": "net"
      }
    }
  },
  "input": {
    "filter": {
      "bpf": "port 53"
    },
    "input_type": "pcap",
    "tap": "default_pcap"
  },
  "kind": "collection"
}

**Comment by lpegoraro** [comment]
I added this PR https://github.com/ns1labs/orb/pull/1415 to check, but I don't have that Dashboard to check the metrics. Testing a bit more..

**Comment by manrodrigues** [comment]
ok 

agent_1 - only dns handler
agent_2 - only net handler
agent_3 - only dhcp handler
agent_4 - dns, net and dhcp policy

![metrics_ok](https://user-images.githubusercontent.com/78241475/180792924-9eb7d1eb-122a-491b-9274-142182348745.gif)
