### ISSUE TITLE
Text Input Improvements

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1492]
The user is not informed about what can be added to the text input.

i.e.: tag input does not accept special characters, name input does not allow spaces...

Add helper text informing the user what kind of input is expected

**Comment by gpazuch** [comment]
related to #1395

**Comment by manrodrigues** [comment]
Dataset text input still need to be improved

![image](https://user-images.githubusercontent.com/78241475/194144045-81244c4a-4fea-421f-a73a-e831ef6e4ae2.png)

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/195419666-23dff7e3-f267-4003-b9b8-e901122fa5a8.png)
