### ISSUE TITLE
Policy view: page shows infinite error after a group is removed

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1526]
When the policy has a dataset whose group was removed from the orb, the page keeps giving error forever.
This happens because the group space in the dataset is empty

![unexisting_group.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/cf88ddc6-c67e-4e69-bf56-55dd64d481d8)

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/b1172ebb-739d-437b-8140-d2abeb06204a)

The purpose of this issue is to include a validation for the empty group field and, in these cases, not make the request.

Steps to reproduce:

- Create a group
- Create a sink
- Create a policy
- Create a dataset linking the group, the sink and the policy
- Remove the group from orb
- Check the policy view page

**Comment by gpazuch** [comment]
@manrodrigues should this field be even sent?
normally backend omits a field when it is undefined.
@lpegoraro

**Comment by lpegoraro** [comment]
I will take a look, seems low hanging fruit, but IMO this looks like a relationship structure and undefined there can cause some unexpected behaviors,  wdyt?

**Comment by gpazuch** [comment]
@brunofariasdeo @manrodrigues 
related to #1543 
shouldn't happen in the manner described here anymore.
