### ISSUE TITLE
Make Search input case insensitive

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1535]
To all filter tools, make sure to use case insensitive match unless specified exact search

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/182905892-699bb6e5-2b2e-4f34-b9d6-4af261ac41c0.png)

![image](https://user-images.githubusercontent.com/78241475/182905963-6b59f5f7-8d50-4700-9c2b-eb6240e9ecd4.png)

![image](https://user-images.githubusercontent.com/78241475/182906039-41d48aab-5565-4df7-8c46-d92f57a9ef0c.png)

![image](https://user-images.githubusercontent.com/78241475/182906109-e2eca37c-587d-442c-b45c-d4e920251862.png)
