### ISSUE TITLE
The user can add only blank space on the tag field

### ISSUE THREAD

**Issue by pfbrasi** [ns1labs/orb#1546]
**Describe the bug**
The user can add only blank space on the tag field

**To Reproduce**
1. Go to Agent Group > New Agent Group
2. Add Agent Group Name and Agent Group Description
3.Add only blank spaces in Add Tag Key and Add Value

**Expected behavior**
Tag key should not accept blank space 

**Screenshots**
![image](https://user-images.githubusercontent.com/83239935/180477235-2d7f50df-1060-4bf4-bf62-dd74d55890a7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 103

**Comment by manrodrigues** [comment]
It's the same issue as #405. Right?
