### ISSUE TITLE
The agent group name exceeds the field limit

### ISSUE THREAD

**Issue by pfbrasi** [ns1labs/orb#1550]
**Describe the bug**
The agent group name exceeds the field limit

**To Reproduce**
1. Go to Agent Group > New Agent Group
2. Add a long name in Agent Group Name 
3. Add a description, tag key, and tag value

**Expected behavior**
The field has a character limit to not overlap the content next to it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/83239935/180479983-bb2962c7-351a-4a85-84c8-d7cc44df63b1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 103

**Comment by manrodrigues** [comment]
ok
