### ISSUE TITLE
Duplicated Sinks showing in Active Datasets list.

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1567]
When the same sink is applied to multiple datasets related to the same policy, the sink appears repeated in all datasets.

![image](https://user-images.githubusercontent.com/78241475/181011254-c774b979-285d-4909-bf0b-9029105da0f6.png)

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/181362667-5164e929-e5e4-4672-a197-49b17ecfc270.png)
