### ISSUE TITLE
Sinks: filter by name is not filtering

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1578]
even after including the name filter in the sink, sinks without the filtered name are displayed in the list:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/a5134803-7b4f-4118-86f4-a6c8256a6a1f)

**Comment by gpazuch** [comment]
@manrodrigues cannot reproduce.
this seems to have been fixed.

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/182891369-9e5d7855-6cf6-4cda-8870-5fccade0e53b.png)

![image](https://user-images.githubusercontent.com/78241475/182891444-ef72f5b1-ec25-4ff1-9e9e-475b760f5777.png)
