### ISSUE TITLE
Add Context to all goroutine calls in Orb Agent

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1619]
Control cancellation and trace of all go routines within Orb Agent

- [ ] Track all go routines in Orb Agent and add context with go routine name
- [ ] Create a function in the agent that cancels the parent context and exit the application.
- [ ] Every time the MQTT fails to reconnect and becomes unable to re-send data to fleet, call the context cancellation and with it the graceful exit of the container.

**Comment by manrodrigues** [comment]
When the agent is stopped the status of the agent must be "offline" and now it's failing with a panic and the agent keeps as online (and then stale..)

We don't want any kind of "panic" on agent logs.. neither when the agent is removed from orb.. the logs needs to be more useful and graceful.
