### ISSUE TITLE
Agent container is exiting in "panic" after remove/stop

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1632]
When the agent is stopped the status of the agent must be "offline" and now it's failing with a panic and the agent keeps as online (and then stale..)

We don't want any kind of "panic" on agent logs.. neither when the agent is removed from orb.. the logs needs to be more useful and graceful.

_Originally posted by @manrodrigues in https://github.com/ns1labs/orb/issues/1619#issuecomment-1208294059_

**Comment by manrodrigues** [comment]
@mclcavalcante I had a power outage here at home while testing the reset scenarios and one of my agents panicked after that:
Full logs:

[_orb-agent-int-testtHlei_logs.txt](https://github.com/ns1labs/orb/files/9362953/_orb-agent-int-testtHlei_logs.txt)

**Comment by lpegoraro** [comment]
For this last comment 

> @lpegoraro @mclcavalcante The agent that stopped without panic while the power outage doesn't reconnect automatically when the energy came back

This scenario is beyond our reach.

There are two probable outcomes when an agent loses the connection, before it asks for the pingresp and after.

1.a. if it loses connection **before** asking the pingresp
2.a. it will make the agent comms wait until reconnect

1.b. if it loses **after** asking the pingresp
2.b. then the agent will log CRITICAL and say that the connection was broken

**Comment by manrodrigues** [comment]
ok
