### ISSUE TITLE
Policies: DNS filters are not being added when policy is created through wizard editor

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1645]
When DNS filters are included on Hanlde modal, it need to be parsed on the API request, but it's not.. so the policies are being created without any DNS filter:

![dns_filters.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/503b09ba-67e3-490c-b432-06a1d6efdf7b)

Expected handler:

```
{
  "handlers": {
    "modules": {
      "default_dns": {
        "filter": {
          "exclude_noerror": "true",
          "only_qname_suffix": [
            ".example.com"
          ],
          "only_rcode": 2
        },
        "type": "dns"
      }
    }
  }
```
Filters missing:

- Only qname
- Only rcode
- exclude no error

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/184703137-adbb389a-ebf2-490d-9a78-87aba27afe8b.png)

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/186957899-74592710-d3e1-4ce7-b6ad-349e63064591.png)
