### ISSUE TITLE
Groups: Response for groups edited using pre existing name (conflict) is returning status code 500

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1667]
Steps to reproduce:

- Create 2 groups
- Make a PUT request on `/api/v1/agent_groups/{group_id}` endpoint (or edit it through Orb UI) using the name of the first group on the second group (the intention is create a conflict error)
- Check the status code

Expected behavior:
status code - 409 (conflict)

Current behavior:
status code - 500: internal server error

![group_duplicated_name.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/4e400433-0eda-4edc-9f1d-8fac46706c8d)

**Comment by lpegoraro** [comment]
Follow the same implementation of the Sinks on #1668 , if you want, you can join these tickets and solve in one PR.
The solution is duplicated, but the root cause is most likely to be the same.

**Comment by manrodrigues** [comment]
ok

![group_conflict](https://user-images.githubusercontent.com/78241475/208092905-902a3401-05f8-4ce0-8af4-bade19ef4c57.gif)
