### ISSUE TITLE
Append `--restart=always` command in docker run command in UI, setting the default for the agent container always restart in cause of stopping/failure

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1676]
Suggestion to make things easier.

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/186731640-e950a188-c49f-406d-9598-dec338e69ec6.png)

![image](https://user-images.githubusercontent.com/78241475/186731763-8f5bbabf-3558-4927-8f94-d50e8fb8b59b.png)
