### ISSUE TITLE
Orb login: Scroll bar is not working on login page

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#172]
The scrollbar is not working, so if an alert message is displayed or the page size is reduced, the user will not be able to access all login options

Check: https://drive.google.com/file/d/14hSJzJ89DRUR_jaEMIgQuqYybaQcALV3/view?usp=sharing

https://drive.google.com/file/d/1bmOJtVKjfrLY60HrKB_2K44_Vs1GhGJZ/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

**Comment by iatdaitan** [comment]
This issue was fixed by another issue.
