### ISSUE TITLE
Orb login: Register an account and request password pages are without correct formatting (orb pattern)

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#174]
It was working better on last version tested

Check: https://drive.google.com/file/d/13dwXYEdKqLTEfL1TOSmUaLVhpdVqhmmH/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

**Comment by gpazuch** [comment]
Removing 'bug' tag

**Comment by manrodrigues** [comment]
-Before delete:
![image](https://user-images.githubusercontent.com/78241475/131879148-0073b98a-9e84-4384-ac36-aa0213c842e2.png)

-After delete:
![image](https://user-images.githubusercontent.com/78241475/131879229-2817f304-8b9a-4954-a48b-7fc8bd3c7c9c.png)


Last commit: 524c586568de6fc04ada81bf594f256aa9d3958a

**Comment by iatdaitan** [comment]
![image](https://user-images.githubusercontent.com/86745196/140173619-1b0f19c5-962f-4239-bd58-e6a5b0df9f77.png)

**Comment by iatdaitan** [comment]
@manrodrigues register looks fine, forgot password will be done in a different task for milestone 0.10.0.
