### ISSUE TITLE
feat(otel-col): trigger and run OTel Collector Instances

### ISSUE THREAD

**Issue by lpegoraro** [ns1labs/orb#1800]
- [x] Test k8s as orchestrator of several sinks
- [x] Connect triggers to kubernetes to spin new sink-otel-collector

Tasks blocked by #1798 and #1799

- [x] Deploy OTel-Collector in K8s Stg
- [x] Deploy OTel-Collector MVP in K8s Kind

**Comment by etaques** [comment]
Done in.
https://github.com/ns1labs/orb/pull/1888

It is running on stg.
