### ISSUE TITLE
Sink Management: texts are overwritten in tables

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#181]
When name_label or description is bigger than the reserved space, texts are being overwritten.

Check: https://drive.google.com/file/d/1ipnDXvAP3NLJMbRcDRr-ukbZaT3HlEDp/view?usp=sharing

Last Commit: 50df003b85d894ec2f3ba7d5d7a913eec1e82e4e

**Comment by gpazuch** [comment]
https://github.com/ns1labs/orb/issues/249
