### ISSUE TITLE
Sinks: config parameter is not being required on sinks creation 

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1853]
Users must not be able to create sinks without specify the configurations. For this reason, "config" parameter must be required. 

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/b5353de3-2ba7-4723-8ad0-ab2566ed6e41)

Currently, config parameter is not being required:

![sink_without_config.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/535ac56d-5b7e-4836-a603-44e99be30956)

**Comment by lpegoraro** [comment]
# Refinement
Define the minimal amount of keys a Config must have for it to be valid.
Today, the minimal is 3, username, password, url, the optional is the opentelemetry, and it will be removed soon.
But I think 2 is valid enough, for creation purposes, in a next update we can add a function to actually validate the config in the sink, and check if the config is valid.

There is a validate() function
on sinks/api/http/requests.go:35
add a code similar to this:
```golang
	keySize := 0
	if req.Config == nil {
		return errors.ErrMalformedEntity
	} else if req.Config.IsApplicable(func(key string, value interface{}) bool {
		if key != "" {
			keySize++
		}
		if keySize > 2 {
			return false
		}
		return true
	}) {
		return errors.ErrMalformedEntity
	}
```
TODOs
- [ ] Check if the implementation above is correct
- [ ] Implement or adapt the implementation accordingly
- [ ] Add unit tests

**Comment by manrodrigues** [comment]
configs is now being required

 
![image](https://user-images.githubusercontent.com/78241475/210264651-4dfbc122-c6e6-4c64-aa4f-9c37f4b1d42c.png)
