### ISSUE TITLE
Agents: when OTEL is active, agent mqtt connection ends with EOF error after a while

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1905]
When OTEL is enabled (`-e ORB_OTEL_ENABLE=true \`), agent get an EOF error after some time running, then the mqtt connection is broken and the agent is not able to receive new information.

**Comment by manrodrigues** [comment]
```
{"level":"info","ts":"2022-10-25T21:43:59.157Z","caller":"otlpmqttexporter/otlp.go:117","msg":"scraped and published metrics","topic":"channels/9b815459-cd1e-4539-9322-977c172bc0c6/messages/otlp/pktvisor/m/a","payload_size_b":617}

{"level":"info","ts":"2022-10-25T21:44:03.823Z","caller":"pktvisor/pktvisor.go:163","msg":"pktvisor stdout","log":"[2022-10-25 21:44:03.822] [visor] [info] REQUEST: GET /api/v1/metrics/app 200"}

{"level":"info","ts":"2022-10-25T21:44:53.822Z","caller":"pktvisor/pktvisor.go:163","msg":"pktvisor stdout","log":"[2022-10-25 21:44:53.822] [visor] [info] REQUEST: GET /api/v1/metrics/app 200"}

{"level":"info","ts":"2022-10-25T21:44:59.278Z","caller":"otlpmqttexporter/otlp.go:117","msg":"scraped and published metrics","topic":"channels/9b815459-cd1e-4539-9322-977c172bc0c6/messages/otlp/pktvisor/m/a","payload_size_b":617}

{"level":"info","ts":"2022-10-25T21:45:43.823Z","caller":"pktvisor/pktvisor.go:163","msg":"pktvisor stdout","log":"[2022-10-25 21:45:43.822] [visor] [info] REQUEST: GET /api/v1/metrics/app 200"}

{"level":"error","ts":"2022-10-25T21:45:59.082Z","caller":"agent/logging.go:49","msg":"ERROR mqtt log","payload":["[client]  ","Connect comms goroutine - error triggered",{}]}
``` 

[_musing_edison_logs.txt](https://github.com/ns1labs/orb/files/9872073/_musing_edison_logs.txt)

**Comment by lpegoraro** [comment]
I tested a few times, trying to replicate, but couldn' t replicate, maybe something we did as enhancement solved this, can you test with latest develop?

**Comment by manrodrigues** [comment]
I was running yesterday and I had this misbehavior:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa98254]
``` 

Not sure if we already have this logs.. but i'm putting here:
 
[_orb-agent-int-testkoemH_logs.txt](https://github.com/ns1labs/orb/files/10086381/_orb-agent-int-testkoemH_logs.txt)

**Comment by manrodrigues** [comment]
Closing this issue based on this slack thread: https://netdev-community.slack.com/archives/C041B9204CF/p1669840539340209

Agent: 68bcd176-b16a-49be-a02d-bc54e25c659b (logs: zealous_gates)..
EOF time: 19:12:45.835Z
MQTT logs:
		2022-11-30 16:12:46	
{"log":"{\"level\":\"warn\",\"message\":\"Broken connection for client: 68bcd176-b16a-49be-a02d-bc54e25c659b with error: failed proxying from MQTT broker to MQTT client : write tcp 127.0.0.1:56904-\u003e127.0.0.1:1883: write: connection reset by peer\",\"ts\":\"2022-11-30T19:12:45.766942033Z\"}\r\n","stream":"stdout","time":"2022-11-30T19:12:45.767109388Z"}
2022-11-30 16:12:46	
{"log":"{\"level\":\"info\",\"message\":\"Disconnect - Client with ID: 68bcd176-b16a-49be-a02d-bc54e25c659b and username 68bcd176-b16a-49be-a02d-bc54e25c659b disconnected\",\"ts\":\"2022-11-30T19:12:45.759649257Z\"}\r\n","stream":"stdout","time":"2022-11-30T19:12:45.759859144Z"}
2022-11-30 16:12:45	
{"log":"19:12:45.759 [warning] client {[],\u003c\u003c\"68bcd176-b16a-49be-a02d-bc54e25c659b\"\u003e\u003e} with username \u003c\u003c\"68bcd176-b16a-49be-a02d-bc54e25c659b\"\u003e\u003e stopped due to keepalive expired\r\r\n","stream":"stdout","time":"2022-11-30T19:12:45.760339499Z"}
Amanda Rodrigues
  [34 minutes ago](https://netdev-community.slack.com/archives/C041B9204CF/p1669843119598519?thread_ts=1669840539.340209&cid=C041B9204CF)
fleet has no "special" logs.. at least not in some level that I have access..


Shannon Weyrick
  [33 minutes ago](https://netdev-community.slack.com/archives/C041B9204CF/p1669843163348679?thread_ts=1669840539.340209&cid=C041B9204CF)
cool ok so i don't see anything particularly problematic there - it really did just time out
