### ISSUE TITLE
Website: menus on all pages bold (as selected) the item above the chosen/exposed item

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#1923]
- side menus on all pages bold (as selected) the item above the chosen/exposed item

![wrong-mark](https://user-images.githubusercontent.com/78241475/196699382-77443fc5-0f7a-4303-a05b-881359ec6c33.gif)

**Comment by gpazuch** [comment]
https://github.com/squidfunk/mkdocs-material/issues/3578

update mkdocs-material-9.0.0b4

**Comment by gpazuch** [comment]
https://github.com/ns1labs/orb-website/commit/76c997f521f08d67bab05f20254abdeb080655b2
https://github.com/ns1labs/orb-website/commit/27cc4bhttps://github.com/ns1labs/orb-website/commit/8f323658f41e90caacf5768b82e091fbdec9aad7aacd893d7ba8461b25715321258ff09634

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/208460246-8861d486-1c72-4ef2-8cb3-2dce4bba460f.png)

![image](https://user-images.githubusercontent.com/78241475/208460332-475c0180-fe36-437b-97b5-9423a48e8980.png)
