### ISSUE TITLE
Pktvisor Dump while running Orb Agent with OTEL

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#2020]
We don't have the isolated scenario that generates the dump, so I'll leave some logs:

Debug logs:

[https://app.zenhub.com/files/340174841/23a2ab9c-c7db-47e8-8d3d-afdaacd1cfd5/download](https://app.zenhub.com/files/340174841/23a2ab9c-c7db-47e8-8d3d-afdaacd1cfd5/download)

Without debug:

[https://app.zenhub.com/files/340174841/9541e7d3-a6dd-4e42-954a-4e5061820604/download](https://app.zenhub.com/files/340174841/9541e7d3-a6dd-4e42-954a-4e5061820604/download)

[https://app.zenhub.com/files/340174841/89181e75-1903-4f90-9aa5-0189b85b636a/download](https://app.zenhub.com/files/340174841/89181e75-1903-4f90-9aa5-0189b85b636a/download)

**Comment by leoparente** [comment]
Issue stopped happening after orb OTEL fix
