### ISSUE TITLE
Datasets: make group field in dataset into selector

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#2056]
Since the user can only choose between existing groups, the group field in a dataset should be a selector (like sink, for example).

Expected change: make group field into selector

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/1db8fae5-d04e-4d1d-bd49-2c5bb6b34b93)

**Comment by gpazuch** [comment]
@manrodrigues we've opted for autocompletion because scrolling through possibly hundreds of agent groups w/o the possibility of filtering could become a nuisance to the user.

Perhaps dropdown select isn't the most effective in this scenario
