### ISSUE TITLE
Agent: Agent creation with agent group description

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#236]
Description for sink creation should be different from agent groups creation

**Comment by manrodrigues** [comment]
![Orb (1)](https://user-images.githubusercontent.com/78241475/132616728-baed3d1d-128a-4ee0-9d34-5fa7280135de.jpg)

**Comment by manrodrigues** [comment]
Expected: 

![Orb (2)](https://user-images.githubusercontent.com/78241475/132616792-da447518-0957-4ef3-8148-905b45879ce1.jpg)

**Comment by iatdaitan** [comment]
This issue was fixed by another issue.
