### ISSUE TITLE
Agent: Number of regions not match (remove Region text)

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#239]
When more than one agent are created with the same tag and location, the counter does not group regions.

**Comment by manrodrigues** [comment]
![Orb (4)](https://user-images.githubusercontent.com/78241475/132617972-b4afd610-3e96-4efb-8c29-26d687c632db.jpg)

**Comment by weyrick** [comment]
no concept of Regions right now so let's remove
