### ISSUE TITLE
Agent: Enabled to create agent without tag

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#240]

**Comment by manrodrigues** [comment]
![Orb (5)](https://user-images.githubusercontent.com/78241475/132618220-5b7d84fa-f0fd-415d-87c1-35bf681d9341.jpg)

**Comment by manrodrigues** [comment]
Note that (location, location) referred to text inserted on location

**Comment by iatdaitan** [comment]
This issue was already fixed.
