### ISSUE TITLE
Name and tags incompletely displayed

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#241]
If the name is longer than 9 characters and there are many tags, the text will be displayed incompletely

**Comment by manrodrigues** [comment]
Review and confirm are correctly displaying:
![Orb (6)](https://user-images.githubusercontent.com/78241475/132618947-bd6a23b1-591e-407a-8b5e-022bde980ec5.jpg)

All agents with incomplete text:

![Orb (7)](https://user-images.githubusercontent.com/78241475/132619072-e0c6f02f-02cd-4773-8319-7d1105f550ef.jpg)

**Comment by gpazuch** [comment]
https://github.com/ns1labs/orb/issues/249

**Comment by manrodrigues** [comment]
I'm reopen this card so that we keep in mind that these usability adjustments are still necessary
- Agent
- Agent Groups
- Sink
- Dataset
- Policy

**Comment by manrodrigues** [comment]
I know that UI must change witth Erica's suggestion... but let's keep it here for now

**Comment by gpazuch** [comment]
![agent-table](https://user-images.githubusercontent.com/1490938/175957341-ef195202-be77-491a-bf5c-0223d2b5264b.gif)

**Comment by gpazuch** [comment]
![1366x768](https://user-images.githubusercontent.com/1490938/175957454-0507506f-0d23-4717-81fd-e4f9f8610907.png)

**Comment by gpazuch** [comment]
![1920x1080](https://user-images.githubusercontent.com/1490938/175957566-4a02a22f-b50f-4ff6-a514-ce228e510d28.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/175959686-ad72325a-08f4-4f36-894a-a8179fb663a1.png)

**Comment by gpazuch** [comment]
![1920x1080](https://user-images.githubusercontent.com/1490938/175963066-32128237-b116-4e10-abec-f0be3d92eb53.png)

**Comment by gpazuch** [comment]
![1366x768](https://user-images.githubusercontent.com/1490938/175971249-5d7cb61f-8f19-4a95-ae49-1eb0efe56879.png)

**Comment by gpazuch** [comment]
![1920x1080](https://user-images.githubusercontent.com/1490938/175972165-d9b6e953-a7ee-4460-847a-6ea757059158.png)

**Comment by gpazuch** [comment]
![1366x768](https://user-images.githubusercontent.com/1490938/175972275-0cd0c28f-c621-431e-888e-cafd3e129fec.png)

**Comment by manrodrigues** [comment]
It's much better for the tags.. but we still need some work on the arrangement of the names :) Lets open another ticket for it.

![name_tags_displayed](https://user-images.githubusercontent.com/78241475/176452636-4efafd20-26fa-4d43-8a2b-f1f3dd111674.gif)
