### ISSUE TITLE
All pages: sorting tool not working on any page

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#383]

**Comment by gpazuch** [comment]
![table](https://user-images.githubusercontent.com/1490938/154743316-0da83a65-da2c-4995-9141-58be09646056.gif)

**Comment by manrodrigues** [comment]
Filter by tags still not working:

![tags_not_working](https://user-images.githubusercontent.com/78241475/157031086-541e9fb1-b270-4e8b-93d6-4d9efef87d43.gif)


Filter by agents matching not working:

![matching_agents_filter](https://user-images.githubusercontent.com/78241475/157031349-70672141-e65b-49c2-bd74-f37a27a59801.gif)


other filters are working fine

**Comment by gpazuch** [comment]
@manrodrigues that would be the sorting.
I haven't enabled sorting by agents version.
Filtering is done via selector on top-right corner of the table, selecting the field to filter with from the dropdown selector.

**Comment by gpazuch** [comment]
@manrodrigues I have also added filter by tags.
Again, the sorting by tags is not enabled, it could be a bit subjective, but I believe I could concatenate all prior to performing the sort on it, applying string comparation only.

**Comment by gpazuch** [comment]
@iatdaitan @manrodrigues https://github.com/ns1labs/orb/pull/921 
I've pushed some fixes to this branch that should fix the sort issue by tags and matching agents number

**Comment by manrodrigues** [comment]
Nice :) Last commit: 32a27c52477e0391def02e8a3dd36376c578f581

![sort_ok](https://user-images.githubusercontent.com/78241475/157317644-358a4627-ab39-4c8e-be36-8ce85a7ef82f.gif)
