### ISSUE TITLE
Policy management: filters field is misplaced and total count is missing

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#384]

**Comment by gpazuch** [comment]
@manrodrigues @iatdaitan I think I fixed the position for filter input [here](https://github.com/ns1labs/orb/commit/d908647feff29c66493a8d2925fc212a18afbe87), but I'm not sure on the total count and the text stating there are no agents yet.

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/157318136-c6973c14-179b-4390-b602-316561332437.png)

@gpazuch yes. The position is fixed, but total count/text when no policies existing is not working yet

**Comment by manrodrigues** [comment]
I'm closing this issue because of #927
