### ISSUE TITLE
All pages: list of view should only be visible when data is fully loaded.

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#395]
Note that when some page is selected, the page loads with the table written that there is no data and the count 0, and after a while correct data appears. Data request is part of load page process and elements should only be visible when correct data is fully loaded (as with the top information bar "x elements and y errors)

**Comment by gpazuch** [comment]
Estimated for all pages, although logic should be the same for each and every one.

**Comment by gpazuch** [comment]
@manrodrigues you mean the whole table/page should not be visible?

**Comment by manrodrigues** [comment]
@gpazuch this is actually a very minor. This is more important considering automated tests than for the users.. The problem is that when we refresh or get in some page, the total of elements is displayed as 0 on the first second. The suggestion was just display the counts when the page is fully loaded..

Check the issue:

![zero](https://user-images.githubusercontent.com/78241475/162960837-ed2e288b-6aeb-4229-8570-66881d2860e4.gif)

but, again, its a very minor and in my opinion very low priority

**Comment by gpazuch** [comment]
I see, though I don't think that's the right approach to it.
The tabular data is dynamic and bound to change at any moment, considering we implement socket comm or even a 1s interval refresh.

Perhaps there is a way of observing the total count value and testing whenever it changes?
