### ISSUE TITLE
Policy Management: Policy creation is not enabled

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#429]
Error message with successful code and back end field not working

**Comment by manrodrigues** [comment]
![policy](https://user-images.githubusercontent.com/78241475/140101454-02b6b9f5-702c-4dc4-899b-632d864146e8.gif)

**Comment by weyrick** [comment]
I am seeing the same error

**Comment by iatdaitan** [comment]
Reopened as it was closed by mistake.
