### ISSUE TITLE
Dataset table is showing Date created and Date Last Received broken columns 

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#431]
Let's remove for now

![Screen Shot 2021-11-03 at 1 57 31 PM](https://user-images.githubusercontent.com/195691/140166077-4451b113-a1f6-4e80-baa1-3a98fbeaee62.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/140321765-0c7517a8-7ffe-47ba-8841-0538380aac9f.png)
this seems to be an issue with backend
@dscabral @iatdaitan 
suggest: label: orb-ui -> orb-backend
