### ISSUE TITLE
Timeout should disconnect user from ORB

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#446]
After a while of no use, the user loses access to the databases, but the account does not appear as logged out on the page, which only returns errors when accessing the backend

**Comment by weyrick** [comment]
yes, the sessions last 24 hours, we should forward them back to the login page when a session is invalid

**Comment by manrodrigues** [comment]
Not seems to be working :/ 

Could you confirm, please? @gpazuch 

![disconnect_user](https://user-images.githubusercontent.com/78241475/171853199-08e2033e-5976-4380-9069-b36089b72a3f.gif)

**Comment by manrodrigues** [comment]
ok 

![logout](https://user-images.githubusercontent.com/78241475/186675178-0936c7de-77b9-415d-a41a-489a08511172.gif)
