### ISSUE TITLE
Agents: warn about agents which are currently online which have no tags

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#464]
Once an agent must have at least one tag to be useful it would be nice to have a warn about agents which don't have any tag.

**Comment by gpazuch** [comment]
Should I warn the user in the Agent Creation page from the get go, or is this a warning to be displayed on agents listing page as well, in the form of a tag, on a bright color, orange or yellow perhaps?

**Comment by weyrick** [comment]
You can't warn at creation because we don't yet no if the agent will have any "agent tags" (set by the orb-agent itself), so the warning would have to show only for agents which are not "new" status but have no tags (orb tags or agents tags)

**Comment by gpazuch** [comment]
related to #640 @iatdaitan ?

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/149016443-d0d2729b-8360-46cd-a597-863c774fb367.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149016468-67ade96d-2206-42d1-9403-5e438106685c.png)

<br>

last commit: https://github.com/ns1labs/orb/commit/89a16c429d25f4e7e611f4b47c2af4179a7a7669
