### ISSUE TITLE
Policy Management: none type of backend is available to choose on policy creation

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#469]
pktvisor is not being interpreted as a backend type and no other option is available

**Comment by manrodrigues** [comment]
![policy1](https://user-images.githubusercontent.com/78241475/140926077-ac6d15c1-ae96-481f-b3c6-4f94a977d360.gif)

**Comment by manrodrigues** [comment]
test - last commit -> f148a1b2710361cedf833ba526662c62735549ee -> merge PR 463

**Comment by gpazuch** [comment]
I have fixed for Agent Policy page, will update other pages soon @manrodrigues
