### ISSUE TITLE
Datasets: once we don't have tags for datasets, there is no reason to have a field for tags on visualization modal and a filter by tags as an option

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#473]

**Comment by manrodrigues** [comment]
![Orb (4)](https://user-images.githubusercontent.com/78241475/140929901-9bb6f837-5d79-40ff-ae41-09ebe305445d.jpg)

**Comment by manrodrigues** [comment]
![Orb (5)](https://user-images.githubusercontent.com/78241475/140929928-8ba79f70-5f31-42dc-a20d-34e9db36e12a.jpg)

**Comment by gpazuch** [comment]
@manrodrigues I believe this issue has been solved recently, possibly duplicate.
Hence no PR for this one.

Could you verify and close this card?

**Comment by manrodrigues** [comment]
@gpazuch I just tested using develop last commit and we still have filter by tags for datasets, as you can see:

![image](https://user-images.githubusercontent.com/78241475/147104174-52bc2e21-008d-40f7-8f22-5cbf6f06c41e.png)

**Comment by gpazuch** [comment]
@manrodrigues good catch, ty, I will have an update on the way
