### ISSUE TITLE
Policy Management: create and edit policy is without "save" option and is saving by "next" option

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#485]
Like all other components, it is expected that when a policy is created or any existing policy is edited, the last page will be a review and confirmation page, with the option to go back and save, but the policy is being saved by clicking " next" button without going through review and confirm. Check:

**Comment by manrodrigues** [comment]
![policy-edit](https://user-images.githubusercontent.com/78241475/141121276-801770f4-ebfd-4516-873d-1f58cda7cce0.gif)

**Comment by manrodrigues** [comment]
![policy-creation](https://user-images.githubusercontent.com/78241475/141131341-9720e9eb-2e30-4c8f-a18a-91d814b1d396.gif)

**Comment by weyrick** [comment]
is this still relevant?

**Comment by manrodrigues** [comment]
Saving by "Save" buttom. ok
![savepolicy](https://user-images.githubusercontent.com/78241475/143054538-c03b4b42-4d63-4ff3-be0a-d8d8cc238aaa.gif)
