### ISSUE TITLE
Policy Management: last modified field is empty on policy view

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#487]

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/141124436-c6209bcb-61d6-40b9-b2b1-ef0df58967e0.png)

**Comment by gpazuch** [comment]
@dscabral do we have this field for agent policies response?

**Comment by dscabral** [comment]
No, we don't. But I think we should create it.
