### ISSUE TITLE
Policy Management: filter by version is not working

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#489]
Check:

**Comment by manrodrigues** [comment]
![version](https://user-images.githubusercontent.com/78241475/141128345-ba7c7ae3-7208-41b1-bb08-62959110698f.gif)

**Comment by gpazuch** [comment]
@manrodrigues I believe this is fixed as of https://github.com/ns1labs/orb/commit/d908647feff29c66493a8d2925fc212a18afbe87

**Comment by manrodrigues** [comment]
@gpazuch please, take a look, for some reason, the version of the policy is not being displayed anymore:

![without_version](https://user-images.githubusercontent.com/78241475/156833147-6bbdb079-ad06-482c-ae81-40ba06a7bf57.gif)

**Comment by gpazuch** [comment]
https://github.com/ns1labs/orb/pull/920
TY @manrodrigues 
I've opened this pull request with fixes regarding agent policy version.

**Comment by manrodrigues** [comment]
Ok! Last commit - 32a27c52477e0391def02e8a3dd36376c578f581

![policy_version_ok](https://user-images.githubusercontent.com/78241475/157315854-ec9b95e1-0fb2-4b5e-b3b9-6eb370ea2b5f.gif)
