### ISSUE TITLE
Sink read modal

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#49]
The user should be able to check the Sink Details of a specific Sink.

https://www.figma.com/proto/5jZNpc8JMsY2Tj3OQJzgxt/Orb-Product-Portal-UI?node-id=353%3A3972&scaling=min-zoom&page-id=277%3A730

According to UI SPEC page must have the following sections and fields.

- Sink Name
- Sink Description
- Service type
- Backend specific data (no password and token)
- Date Created

**Comment by gpazuch** [comment]
There is some specific information on backend still missing on this modal.
