### ISSUE TITLE
Policy Management: filter by name is saving status of the first character

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#490]
when the name is cleared, all policies should be re-displayed, but still filtering by first status. Check:

**Comment by manrodrigues** [comment]
![name-filter](https://user-images.githubusercontent.com/78241475/141129293-dd6ed0fb-b2f5-40f8-b4fd-4f4e0c985c7b.gif)

**Comment by gpazuch** [comment]
@manrodrigues can you verify this is still the case after [this merge](https://github.com/ns1labs/orb/commit/d908647feff29c66493a8d2925fc212a18afbe87)?

**Comment by manrodrigues** [comment]
ok

![filter_saving_last_status](https://user-images.githubusercontent.com/78241475/157030870-3b4daca5-72de-4897-acc1-d9e470d5e2c1.gif)
