### ISSUE TITLE
suggest handler names based on template "handler_type+#"

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#507]
The handler name/label should be suggested and prefilled into the input box by combining the the handler type and a number. for example if they want to add a "dns" handler, suggest "dns1" for the first one, "dns2" for the second, etc. they can change it if they want.

In the future, we may consider removing this altogether - there may be no good reason to let them choose the name, we may be always able to generate.

**Comment by gpazuch** [comment]
I think this shouldn't take long to implement. ~1.5 hour
Just one thing that comes to mind is checking for this pattern in already saved handlers, like, on the event of the user editing those and having it suggest something useful.
