### ISSUE TITLE
Add data-tag-qa into all UIs pages

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#540]

**Comment by gpazuch** [comment]
https://github.com/ns1labs/orb/wiki/UI-QA-Automation-Tags
This task is to replicate IDing each important field or element in the HTML, like explained in the article above.
It is not complex, although it should demand some time to cover all pages, hence the estimation

**Comment by gpazuch** [comment]
I believe this is not in use anymore, and therefore should be stripped from the code.
@manrodrigues could you confirm that, and if so, close this issue?

**Comment by gpazuch** [comment]
@iatdaitan pending close

**Comment by gpazuch** [comment]
this issue is obsolete/irrelevant in current context.
