### ISSUE TITLE
Adjust nightwatch automated tests to handle new UI

### ISSUE THREAD

**Issue by stefano-daitan** [ns1labs/orb#583]
The UI has been changed in 0.9.0 and that broke some automation done as part of the nightwatch scripts.
These broken tests are yet to be identified and should updated to handle the new UI.

Acceptance criteria:
- All nightwatch test scripts run successfully

**Comment by manrodrigues** [comment]
Manage the containers using nigthwatch.js brings to the project higher complexity than we want. So we agreed to develop all the automated tests (UI + API) using python (selenium + behave, in UI case). Because of that, i'm closing this card. Existing tests cases will be rewrite in python.
