### ISSUE TITLE
Agents: unable to edit agent without a tag

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#610]
Tested on branch develop. Last commit: 99913cd61955eb3fd0e0fd44a725414fc9d1cfaf. <br>
If an agent doesn't have at least on tag, edition is not enabled <br>
![agent_without_tag](https://user-images.githubusercontent.com/78241475/146213408-be958e94-ae92-466d-9a7c-bb8a6b56c202.gif)
<br>
![agent_without_tag2](https://user-images.githubusercontent.com/78241475/146213438-e33895d5-d1a1-46b8-81c0-5f0d78a909df.gif)

**Comment by iatdaitan** [comment]
@dscabral could you please check this issue?

**Comment by manrodrigues** [comment]
@dscabral now the error message is "ok".. can you check why is like this?

Xin screen:

https://files.slack.com/files-pri/T01QM02PK29-F02UH12854N/screenshot__1100_.png

**Comment by gpazuch** [comment]
![no_tag_agent: case 1](https://user-images.githubusercontent.com/1490938/150545744-aff1e896-c59f-49eb-97d8-fa274244668e.gif)

case 1:
* create agent with no tag
* edit agent, add one tag
* save agent
* it works
* edit agent one more time
* remove tags
* save it
* error 400

Case 2: 
* Create one agent - no tags
* edit agent, no changes
* 400 error

It seems like it won't allow tags to be removed

**Comment by gpazuch** [comment]
payloads  
----------------------------------
* creation with no tags  
----------------------------------
`{"name":"no_tag_agent","orb_tags":{},"validate_only":false}  
`
* edit and do not modify, try and save (NOT WORKING)
![image](https://user-images.githubusercontent.com/1490938/150554312-23c3e1e8-9fe0-4469-8a72-99ba62ccbc0d.png)
`{"name":"no_tag_agent","orb_tags":{},"validate_only":false,"id":"68eb9e2f-9f73-40b8-b5aa-eb67fa7d26b4"}`

* go back, add a tag and save it
`{"name":"no_tag_agent","orb_tags":{"one_tag":"true"},"validate_only":false,"id":"68eb9e2f-9f73-40b8-b5aa-eb67fa7d26b4"}`

* edit again and remove the tag - ERROR 400
`{"name":"no_tag_agent","orb_tags":{},"validate_only":false,"id":"68eb9e2f-9f73-40b8-b5aa-eb67fa7d26b4"}`

***********************************************
-------------------------------
* creation with one tag
-------------------------------
`{"name":"one_tag_agent","orb_tags":{"one_tag":"true"},"validate_only":false}`  

@dscabral should I not send orb_tags as empty object when deleting the tags? I believe that's what's causing the error.

**Comment by gpazuch** [comment]
`{"name":"no_tag_agent","validate_only":false,"id":"68eb9e2f-9f73-40b8-b5aa-eb67fa7d26b4"}`

omitting the orb_tag field when no tags are present doesn't allow saving the agent.

**Comment by dscabral** [comment]
We have a validation for agent_tags on edition... if you don't send it, it'll not edit the agent..
We should change it.. but if you have a valid agent with tags... and then send a agent to edit and forget to send the tags... it'll be overwritten

**Comment by manrodrigues** [comment]
Fixed

Last commit: fa3629fb4dd4adc821d788fade84c2ef6c3c81fe

![agent_without_tag](https://user-images.githubusercontent.com/78241475/151803250-a89cbccc-52d5-49aa-b72f-bda294c2ea19.gif)
