### ISSUE TITLE
Agents: Agent version field is empty on agent view

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#611]
Tested on branch develop. Last commit: 99913cd61955eb3fd0e0fd44a725414fc9d1cfaf. <br>
![Orb](https://user-images.githubusercontent.com/78241475/146214038-4b5cba56-7610-4ca4-b593-bd9e2f97ff60.png)

**Comment by iatdaitan** [comment]
@dscabral could you please check if the service is returning the version?

@weyrick in that case when the service doesn't return the version what should we show as default?

**Comment by dscabral** [comment]
Before provisioning the agent we don't have the version value... because it's the docker image version which is used on the agent... So we can explain it on the interface or just hide this field before the agent had been provisioned.

**Comment by manrodrigues** [comment]
I found out that the card description is not enough. I'm sorry. Sure. After provisioning agent, version is displayed correctly. Maybe it's not a bug, but an enhancement.


![image](https://user-images.githubusercontent.com/78241475/146373285-77b107aa-a12a-40c0-b232-0fe1e6c34cd8.png)

**Comment by iatdaitan** [comment]
> I found out that the card description is not enough. I'm sorry. Sure. After provisioning agent, version is displayed correctly. Maybe it's not a bug, but an enhancement.
> 
> ![image](https://user-images.githubusercontent.com/78241475/146373285-77b107aa-a12a-40c0-b232-0fe1e6c34cd8.png)

Thank you @dscabral and @manrodrigues 

I am going to check with @weyrick what should be the default when the agent isn't provisioned yet.

**Comment by manrodrigues** [comment]
closing this issue based on #895
