### ISSUE TITLE
Agent Groups: not enabled to click on agent that matches

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#616]
Tested on branch develop. Last commit: 99913cd61955eb3fd0e0fd44a725414fc9d1cfaf. <br>
User should be enabled to click in a matching agent and open the agent view <br>
![click_match_agent](https://user-images.githubusercontent.com/78241475/146219135-732c4a3e-2f10-4d08-9273-25a2f978af7b.gif)

**Comment by iatdaitan** [comment]
The modal agent list view was designed that way. Going to label this issue as an enhancement.
