### ISSUE TITLE
Policy: When all agents online and offline are removed from orb, user is blocked to edit a policy

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#620]
Tested on branch develop. Last commit: 99913cd61955eb3fd0e0fd44a725414fc9d1cfaf. <br>

If there is an agent online or even offline, user can edit a policy. But, if just new agents remain  or there is no agent, user is not allowed to edit policy. <br>
![edit-policy](https://user-images.githubusercontent.com/78241475/146252691-59ac5619-e26a-4b06-adaa-50732b85f03a.gif)

**Comment by manrodrigues** [comment]
Not fixed: 
![policy_25_10](https://user-images.githubusercontent.com/78241475/150987007-a3eefc03-6dec-4dd6-b293-39abef477af3.gif)

**Comment by gpazuch** [comment]
To create or edit a policy requires that agents are available to be selected.

What is the expected behavior for this scenario? @iatdaitan

**Comment by manrodrigues** [comment]
@iatdaitan  This is not solved yet.. actually, I believe that we don't even know exactly how to solve this issue.

**Comment by manrodrigues** [comment]
I'm closing this issue based on edit through yaml/json option:

![image](https://user-images.githubusercontent.com/78241475/179260388-f2f6fb5f-6d95-4afd-b9c9-b9bb2bceabea.png)

![image](https://user-images.githubusercontent.com/78241475/179260474-040c48fe-3f70-456c-b6b9-acffdc9a22b9.png)
