### ISSUE TITLE
Reorder menu to match documentation

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#624]
Although the user is allowed to follow a different path during the use of Orb, it makes sense to show the information as it is stated on the documentation to increase UX.

This issue aims to match the menu according to the path followed on the Orb Documentation.

- Fleet Management
-- Agents
-- Agent Groups
- Sink Management
- Dataset Explorer
-- Policy Management
-- Datasets

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/146580637-2a41b373-24c3-4d7d-b96f-b8abb58a4bac.png)
