### ISSUE TITLE
Set tab order of form controls

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#638]
To improve the UX for users who want to navigate through Orb form using the keyboard we need to set the tav order of form controls as follow.

1. Each hit of the tab should redirect the user to the field above the current one.
2. When reaching the last field of the form the hit of the tab button should redirect the user to the "NEXT" button.

** If the user press ENTER it should "submit" the form as the "NEXT" button does.
![image](https://user-images.githubusercontent.com/86745196/146551819-d494bacd-d280-45af-8c46-07572675ac87.png)

--

For the tags form:

1. The tab should take the user to the field/button on the right, and then to the "NEXT" button.
2. If the user is on the "Value"  field and hit "ENTER" it should add the pair of "Key and Value" as the "+" do.

![image](https://user-images.githubusercontent.com/86745196/146553554-0df815b9-e680-4690-a20b-51f6714bc1c1.png)

create/edit forms pages
- [x] agent
- [x] agent group
- [ ] agent policy
- [x] dataset
- [x] sink

**Comment by manrodrigues** [comment]
Ok

#993 and #1014 are the only improvements needed. Everything else is working fine.
