### ISSUE TITLE
Add note to Agent tag form when there is no tags created

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#640]
An agent may have tags created at the edge or on Orb UI. Besides being used to make the organization easier, Agents tags are used to match them when creating an Agent Group. So, leaving an Agent without tags may block the user from matching it during the Agent Group creation.

To make it clear on Orb UI, the issue aims to add two notes, one inside the list view and another one inside the step Orb Tags.

List view:
"No tags were created."

![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/879ab93a-4e3f-42f6-806e-3d6656e89ef2)

Orb Tag Step:
"Agent tags were optional and may be set here or when you are provisioning an Agent. The lack of tags will block an Agent to be matched during the Agent Group creation."

* Once the user adds any tag, we may hide the message.

![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/837763a1-86fd-4d7b-86ef-b4c96727bbc2)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/148593541-36f994ae-9f68-4208-aad0-26f315d80f35.png)
![image](https://user-images.githubusercontent.com/1490938/148593581-d7c7a144-d8bb-49d5-9e09-c5ad7e655b53.png)
![image](https://user-images.githubusercontent.com/1490938/148593611-b9c74550-2ab0-4760-bd66-c68ef0429e25.png)

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/149016443-d0d2729b-8360-46cd-a597-863c774fb367.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149016468-67ade96d-2206-42d1-9403-5e438106685c.png)

<br>

last commit: https://github.com/ns1labs/orb/commit/89a16c429d25f4e7e611f4b47c2af4179a7a7669
