### ISSUE TITLE
Change the color of MOCK text on provisioning command

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#641]

**Comment by manrodrigues** [comment]
Tested using last commit - 0fe8fef3201cc31e7a7da8faed1aecb17a0185e0

<br>

![image](https://user-images.githubusercontent.com/78241475/148785665-6398e26e-c43d-4e45-a7dd-00da3cd738f6.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/148785718-7f500f2d-81f0-47a1-9107-dc21a74c141f.png)
