### ISSUE TITLE
add "e.g. " to placeholder examples

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#643]
Users may be confused about the placeholders. So, to avoid it, this issue aims to add "e.g." before the placeholder example.

**Comment by gpazuch** [comment]
@iatdaitan do you recon we should do this at 
![image](https://user-images.githubusercontent.com/1490938/149214719-c48b01fc-3157-4434-90eb-711d379d2c12.png) 
the backend/configuration or should I just hardcode add it to each placeholder?
