### ISSUE TITLE
Improve unit-test coverage of fleet service

### ISSUE THREAD

**Issue by ghost** [ns1labs/orb#652]
@dscabral to add a description

coverage must be at least 80% (statement)

**Comment by mclcavalcante** [comment]
### Current unit tests coverage of fleet service
![image](https://user-images.githubusercontent.com/86990690/147590229-c80f272a-de56-4ea8-9270-ebfea71e0d92.png)
![image](https://user-images.githubusercontent.com/86990690/147590303-6b99666e-c951-4e9c-97ac-51a5d44a0beb.png)

**Comment by mclcavalcante** [comment]
### Current unit tests coverage of data access layer
![image](https://user-images.githubusercontent.com/86990690/147590532-8b09f89f-8238-4faa-897c-9895ca12bddc.png)
![image](https://user-images.githubusercontent.com/86990690/147590587-928bc476-4525-470d-aca6-0155ec820619.png)

**Comment by mclcavalcante** [comment]
Current unit tests coverage of api
![image](https://user-images.githubusercontent.com/86990690/147591082-c68dff4e-a25e-4ebd-b31f-7d1ad91c6775.png)
![image](https://user-images.githubusercontent.com/86990690/147591254-326a4ab7-c3bb-4ca8-8bcf-90f88e10cbe4.png)
