### ISSUE TITLE
Improve unit test coverage of policies service

### ISSUE THREAD

**Issue by ghost** [ns1labs/orb#653]
@dscabral to add description

**Comment by mclcavalcante** [comment]
###Current Unit tests coverage of data access layer
![image](https://user-images.githubusercontent.com/86990690/150023430-dbc6365a-e00c-4f1b-b099-db328b09d476.png)

###Current Unit tests coverage of policy service
![image](https://user-images.githubusercontent.com/86990690/150024158-d459b0af-128c-4078-9bdd-a3b5438e2496.png)

###Current Unit tests coverage of API
![image](https://user-images.githubusercontent.com/86990690/150024882-20ee57e5-d5ff-4784-9084-0eaa8457ca5a.png)
![image](https://user-images.githubusercontent.com/86990690/150024987-43f6c412-70f0-4ab2-b6c6-2f1b1d7601f3.png)

**Comment by mclcavalcante** [comment]
### Updated unit tests coverage of data access layer with this approach
![image](https://user-images.githubusercontent.com/86990690/150413086-56a0446c-93a4-41b8-89f0-b688d8d191b8.png)

### Updated unit tests coverage of policy service
![image](https://user-images.githubusercontent.com/86990690/150413291-4fa9f4ee-2b2d-4cf7-9733-d5764b091390.png)

### Updated unit tests coverage of API
![image](https://user-images.githubusercontent.com/86990690/150413737-685902de-11ea-4905-9db2-08b543784f66.png)
![image](https://user-images.githubusercontent.com/86990690/150413848-dff40e41-10d2-4fb7-b310-34b992eab793.png)
