### ISSUE TITLE
Evaluate code coverage before allowing a PR to be merged

### ISSUE THREAD

**Issue by ghost** [ns1labs/orb#666]
To guarantee a minimum level of quality, we must ensure that all modules of this project are unit-tested
Therefore, whenever a PR is created/updated we must enforce that the code coverage of each module of this project is above a certain threshold.

Initially this should be applied to back-end code only.

The idea is to run unit tests of each backend module (golang) and capture their coverage. Then, we should add either passing a Github status saying that all modules are above the coverage threshold, or a failure github status mentioning which modules don't have sufficient coverage.

Suggestion: start with what Intellij uses to run tests getting coverage. Example:
```shell
go test -json ./... -covermode=atomic -coverprofile ~/go_test_orb.out
```
The tests and coverage report evaluation should be done as part of github actions.

Acceptance criteria:
- There is a defined unit-test coverage threshold (maybe 70 or 80%?)
- Github only allows PRs to be merged if each back-end module coverage is above the threshold

**Comment by lpegoraro** [comment]
only go code for now!

**Comment by etaques** [comment]
Code coverage analisys Done!

![image.png](https://images.zenhubusercontent.com/621ce94d7492e430afadf14e/68871441-4edc-4e03-916e-861723c0c8dd)

Also Im refreshing go-report card
![image.png](https://images.zenhubusercontent.com/621ce94d7492e430afadf14e/d65287f0-82d5-46ce-bee2-12279985f055)
