### ISSUE TITLE
orb-sinker and pktvisor prometheus are producing different metric series

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#670]
orb-sinker converts pktvisor JSON to prometheus, but it's creating different names than native pktvisor prometheus. This results in broken dashboards, so the names need to be the same.

**Comment by weyrick** [comment]
pktvisor native Prometheus:
![Screen Shot 2021-12-21 at 3.58.07 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/14673158-8091-4125-aae6-d99c6fc4bf61)
![Screen Shot 2021-12-21 at 3.58.20 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/f8dc4481-7210-48a8-b79e-d04ebd118c8c)
![Screen Shot 2021-12-21 at 3.58.31 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/be47c89e-edd2-4d05-9e40-09a8df2ca8ef)
![Screen Shot 2021-12-21 at 3.58.48 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/6d213b67-77e4-44a0-8ccf-ed058db645af)

orb-sinker:
![Screen Shot 2021-12-21 at 3.59.19 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/c51660f8-ac5b-4893-a0e2-94ce1d0834fd)
![Screen Shot 2021-12-21 at 3.59.32 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/69d127ab-c4ab-4e9a-8930-ab64370a28a5)
![Screen Shot 2021-12-21 at 3.59.44 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/b313e4a8-b33d-4fec-80ae-25c0e7153482)
![Screen Shot 2021-12-21 at 3.59.50 PM.png](https://images.zenhubusercontent.com/619405487b3b8f4c04108cf3/d64a1e18-939b-4ef5-a4b3-a754ff846bc9)

**Comment by weyrick** [comment]
BTW metrics are case sensitive, so the case needs to match too

**Comment by manrodrigues** [comment]
Names of metrics from orb-sinker is still different of prometheus metrics

<br>

New grafana account without any metrics:

<br>

![image](https://user-images.githubusercontent.com/78241475/149139624-8cea9ac4-9c72-47e7-bff1-a63b39eb009b.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149139656-bfbb1da9-b875-4cdf-a28e-2d6168a149d9.png)

<br>

Metrics sent using last commit -> df5363daee519bbbd9164544513d937821e17d20
and last orb-agent available (docker pull ns1labs/orb-agent:develop) 

<br>

![image](https://user-images.githubusercontent.com/78241475/149140937-146b52d4-dbbe-46c2-9686-ff6ff1909a0d.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149140981-1e0f3686-0061-46c6-9511-ce4ed8c29656.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149141009-dc42a676-8a51-4a58-b446-97e670b3453e.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149141049-c45046ce-5502-4d6b-b1be-c96467f8969a.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/149141088-0ce7a798-c9d8-4ff2-aefa-1374ecd491c0.png)
