### ISSUE TITLE
Policy Management: Handler Configuration not being sent

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#673]
Issue: Handler Configuration is not being sent with the request json.

How to: Create new policy, select handler with configuration fields, create policy, verify request is sent withouth further information on each handler.

**Comment by manrodrigues** [comment]
handlers ok
tested using last commit ced96e3bf3be6de5d4567ea643faceb2d27f057b

![image](https://user-images.githubusercontent.com/78241475/147939165-cad166ca-6112-46be-875f-8be204a94cdc.png)
