### ISSUE TITLE
Policy Management: Input type shouldn't be selectable

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#674]
Remove selector for input type and show input type according to agent configuration

How to: create Policy.

After selection of tap, it is still possible to choose input type.

Remove dropdown and display input type when selecting tap.

**Comment by manrodrigues** [comment]
tested using last commit ced96e3bf3be6de5d4567ea643faceb2d27f057b
![image](https://user-images.githubusercontent.com/78241475/147938224-00ff7b8a-a5bf-47ba-8a93-d3ec5ec38bf3.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/147938266-25d3a0cc-23c9-4f9d-9de6-6b0ecf84a078.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/147938180-72255061-e573-42df-90f6-da8914748912.png)
