### ISSUE TITLE
Policy Management: pcap configuration is breaking page

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#675]
There is a bug when trying to read 'pcap_source' config object, which breaks the page.

Find ways to *break gracefully* for future additions to supported agent configurations.

Fix current pcap configuration bug to display agent configuration detaisl.

**Comment by manrodrigues** [comment]
tested using last commit ced96e3bf3be6de5d4567ea643faceb2d27f057b

![image](https://user-images.githubusercontent.com/78241475/147937569-b75e9e63-59de-4876-b5f3-c641fd3a036b.png)
