### ISSUE TITLE
Add list of taps / capabilities for current agent on agent view page

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#676]
- [ ] Add list of taps / capabilities for current agent.
- [ ] Expose information from data in last_hb_data field

**Comment by weyrick** [comment]
Example of backend data for an agent: taps and version
```
                "data": {
                    "taps": {
                        "default_pcap": {
                            "config": {
                                "host_spec": "192.168.0.54/32,192.168.0.55/32,127.0.0.1/32",
                                "iface": "enp3s0"
                            },
                            "input_type": "pcap",
                            "interface": "visor.module.input/1.0"
                        },
                        "dnstap": {
                            "config": {
                                "socket": "/root/dnstap.sock"
                            },
                            "input_type": "dnstap",
                            "interface": "visor.module.input/1.0"
                        }
                    }
                },
                "version": "3.4.0-develop"
            }
        },
```
Example of backend data from agent listing the state of current policies
```
        "policy_state": {
            "0c4818ae-75c8-4359-aaf9-bdd8432cf577": {
                "datasets": [
                    "aec80952-1434-48a0-8d9c-d91c0d9951ce"
                ],
                "state": "running"
            },
            "1f314929-6677-461c-b6ea-c9c3230ad4ce": {
                "datasets": [
                    "bf92a73d-9dc1-457c-a3d1-7732724432df"
                ],
                "state": "running"
            },
            "811c5953-9ab3-45be-8353-08136144944a": {
                "datasets": [
                    "42d8e6dd-ac1a-47e6-b32b-a18746bddb42"
                ],
                "error":"500 invalid schema",
                "state":"failed_to_apply"
             }
            }
        }
```

**Comment by gpazuch** [comment]
@iatdaitan I noticed agent is returning policy.name as empty string.

Should I query policies and services to gather their names?

I believe I'll have to query datasets for group names, agent only shows their IDs as well.

```
{
  "id": "e3a87773-4d63-477d-9cd7-182ac99799f2",
  "name": "test_agent",
  "channel_id": "3462fdc6-1c91-4101-8183-e52b024d0336",
  "agent_tags": { },
  "orb_tags": {
    "test": "true"
  },
  "ts_created": "2022-02-09T15:21:18.620704Z",
  "agent_metadata": {
    "backends": {
      "pktvisor": {
        "data": {
          "taps": {
            "default_pcap": {
              "config": {
                "iface": "enp0s31f6"
              },
              "input_type": "pcap",
              "interface": "visor.module.input/1.0"
            }
          }
        },
        "version": "4.1.0-develop-1309a90"
      }
    },
    "orb_agent": {
      "version": "0.12.0-develop"
    }
  },
  "state": "online",
  "last_hb_data": {
    "backend_state": {
      "pktvisor": {
        "state": "running"
      }
    },
    "group_state": null,
    "policy_state": {
      "5c05b8d0-d247-4b40-bba9-727701d3ce11": {
        "datasets": [
          "c0a42366-22dd-4ee2-baa1-35b5b4cab6d1"
        ],
        "name": "",
        "state": "running"
      }
    }
  },
  "ts_last_hb": "2022-02-09T15:57:14.689068Z"
}
```

**Comment by manrodrigues** [comment]
list of taps / capabilities for current agent:

ok.. we have the lists... 
![image](https://user-images.githubusercontent.com/78241475/155653136-ba4a0c25-cad8-4ddb-bb23-eba6d2824560.png)


but we also have some problems:

1) taps are only displayed if a dataset is linked with the agent (taps is related to the agent.. not need to have a dataset to have taps)

![image](https://user-images.githubusercontent.com/78241475/155653987-9567a611-60f7-4fc5-bac7-5281f81938b2.png)


2) Policies are listing all existing dataset (not only the related one):

![image](https://user-images.githubusercontent.com/78241475/155653417-1eb9fe5e-65d7-4cb6-bd79-cd945b8d343b.png)

Check that, in this case, despite what is being displayed on UI, each policy is linked with only one dataset:

![image](https://user-images.githubusercontent.com/78241475/155653499-e62e65f2-17d1-46ca-a96f-855934c40175.png)


3) When all datasets are removed, it takes some seconds to this modification reflects on agent's heartbeat (backend problem), but it is failing the agent view:

![image](https://user-images.githubusercontent.com/78241475/155653843-fce31d2c-a367-4e1f-b9be-f3a2d074eb4d.png)


And, quick question: when we should have capabilities?

**Comment by manrodrigues** [comment]
i'm closing this issue because of #895 #896 #897
