### ISSUE TITLE
Datasets: Its not easy to deploy a dataset connection 

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#692]
Datasets details displays linked group, policy and sink by ID, so its not clear what element should be changed or removed (note that even when user have few policies, groups or sinks, the ID is not displayed for any of them).  Also the user is not able to sort by ID, so this shouldn't be the identifier.

<br>

![image](https://user-images.githubusercontent.com/78241475/147577271-756844a7-b80a-4b5b-8ad7-78b33c66fc9e.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/147577376-c74fb3f6-fc43-4e94-95a6-4bba5457e21c.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/147577418-0b814b0a-20e0-4df0-9ea3-035cf8322ad6.png)

<br>

expected result:
group, sink and policy related to a datasets should be displayed by their own name

**Comment by gpazuch** [comment]
We could open a new card for this to allow it to fail gracefully.
I'm not sure how to deal with the dataset presented, but I'm sure I can display a message and disable the selectors when datasets become invalid because of deleted members.

**Comment by manrodrigues** [comment]
Closing this card because #746 is already opened
