### ISSUE TITLE
API: ts_created not working

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#696]
ts_created for sinks and for agents is ok, but for datasets and for groups ts_created is ""ts_created": "0001-01-01T00:00:00Z" in all responses. 
for policy there is no ts_created displayed.

It turns debug logs very difficult because user is not enable to know the time that some element was create and at what point should the logs be exposed.

![image](https://user-images.githubusercontent.com/78241475/147672205-19bfb519-af09-4310-a069-f18deb6175e4.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/147672706-0ec8f2d8-9c0f-42dd-a6b1-0771ff3f5640.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/147672748-79250ce8-ffc6-4d49-8260-efa3c4ab9fff.png)

**Comment by iatdaitan** [comment]
@dscabral is this issue fixed already ?

**Comment by manrodrigues** [comment]
@iatdaitan no. For policies, now, we have ts field with correct data, but for groups and datasets is still "0001-01-01T00:00:00Z"

**Comment by manrodrigues** [comment]
ok :) 

![image](https://user-images.githubusercontent.com/78241475/172250287-c90e9d3c-6861-4639-84d7-7e2dda892d5e.png)

![image](https://user-images.githubusercontent.com/78241475/172250555-ace566be-7b2e-44c7-997b-268a92466d07.png)

![image](https://user-images.githubusercontent.com/78241475/172250611-786797d0-8620-4373-b67f-7a0e56274ca4.png)
