### ISSUE TITLE
elide agent_metadata and last_hb_data in GET agent list

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#700]
Currently we return all `agent_metadata` and `last_hb_data` in the `GET /agents`. This is too much data, we should not include these fields by default - they should only be included in the specific `GET /agents/:id` endpoint.

**Comment by manrodrigues** [comment]
Ok. agent_metadata and last_hb_data is only included on GET /agents/:id endpoint

<br>

![image](https://user-images.githubusercontent.com/78241475/148220846-1f24f975-0b67-4f07-a939-c6f87b61af7d.png)

<br>

![image](https://user-images.githubusercontent.com/78241475/148221216-99777794-882a-4bac-9596-330b636baf5c.png)

<br>

{"id":"6e0fa195-023b-4847-abbb-a47eb8c948a0","name":"test_agent_name_KnLBBgIcZj","channel_id":"acbeaf53-2abf-4d46-be1b-eb6a04748212","agent_tags":{},"orb_tags":{"test_tag_key_xxmH":"test_tag_value_ZYtV"},"ts_created":"2022-01-05T12:42:27.833751Z","`agent_metadata`**":{"backends":{"pktvisor":{"data":{"taps":{"default_pcap":{"config":{"iface":"mock","pcap_source":"mock"},"input_type":"pcap","interface":"visor.module.input/1.0"}}},"version":"3.4.0-develop"}},"orb_agent":{"version":"0.10.0"}},"state":"online","`last_hb_data`":{"backend_state":{"pktvisor":{"state":"running"}},"policy_state":{"0ff68f5e-cf34-4c19-bfd8-c269de310a76":{"datasets":["8faefc34-789e-47d2-bb4f-a00639773989"],"state":"running"},"966aa1f9-f2ca-49c3-a985-a830fe4a251b":{"datasets":["8839a91f-44da-4a1d-a979-f0c72432d512"],"state":"running"}}},"ts_last_hb":"2022-01-05T12:55:29.077854Z"}**

**Comment by manrodrigues** [comment]
But, once data is not included, should we have the fields as "null" in the GET/agents endpoint? I mean, it's documented somewhere that even though in GET/agents it's null, in GET/agents/:id? Because, on first impression, accessing only GET/agents looks like it's a bug and the data doesn't exist. What do you think about @weyrick @dscabral ?

**Comment by manrodrigues** [comment]
#727 will remember us to change it
