### ISSUE TITLE
Agent container logs: Log of when a policy fails to be removed has level "warn" but error response 404

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#706]
Steps to reproduce:

Create new agent (agent 1)
Provision agent container
Create new agent groups with same tag as agent 1
Create new policy
Create dataset linking group (referred to agent 1), policy and sink
Remove the dataset

Expected results:
When something fails, level of log should be an "error"

Current result:
Log level is a "warn" but with error code (404)

**{"level":"warn","ts":1640866005.1662443,"caller":"policyMgr/manager.go:134","msg":"policy failed to remove","policy_id":"39e1f058-3f9a-4fff-a2e5-11705a44539d","error":"404 policy does not exists"}**
{"level":"info","ts":1640866016.3241906,"caller":"pktvisor/pktvisor.go:230","msg":"pktvisor stdout","log":"[2021-12-30 12:06:56.324] [visor] [info] REQUEST: GET /api/v1/policies/__all/metrics/bucket/1 200"}
{"level":"info","ts":1640866016.326133,"caller":"pktvisor/pktvisor.go:297","msg":"scraped metrics for policy","policy":"policy5","policy_id":"39e1f058-3f9a-4fff-a2e5-11705a44539d","payload_size_b":3060}

**Comment by manrodrigues** [comment]
{"level":"warn","ts":1640872335.5744305,"caller":"pktvisor/pktvisor.go:160","msg":"yaml policy application failure","policy_id":"c3a96ddd-9496-43a6-8924-16a85ddf3314","policy":"version: "1.0"\nvisor:\n policies:\n test_policy_name_BrURjEnSAH:\n handlers:\n modules:\n handler_dns_1:\n type: dns\n handler_net_1:\n type: net\n input:\n input_type: pcap\n tap: default_pcap\n kind: collection\n"}
{"level":"info","ts":1640872335.5744474,"caller":"pktvisor/pktvisor.go:230","msg":"pktvisor stdout","log":"[2021-12-30 13:52:15.574] [visor] [error] {"error":"policy with name 'test_policy_name_BrURjEnSAH' already defined"}"}

**Comment by weyrick** [comment]
This is interesting - if policy removal fails, it indicates state of the agent was different from what state of the control plane thought it was. But it's hard to know how to recover here - it should probably act as if Reset RPC was sent, to get back into a sync'd state

**Comment by manrodrigues** [comment]
Closing it because i'm unable to reproduce it again
