### ISSUE TITLE
Policies: when a policy is edited logs displays an error

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#709]
Log level "warn" with error message when an edition is applied to a policy. Note that, despite this, the policy is modified in the backend.

{"level":"warn","ts":1640872335.5744305,"caller":"pktvisor/pktvisor.go:160","msg":"yaml policy application failure","policy_id":"c3a96ddd-9496-43a6-8924-16a85ddf3314","policy":"version: \"1.0\"\nvisor:\n    policies:\n        test_policy_name_BrURjEnSAH:\n            handlers:\n                modules:\n                    handler_dns_1:\n                        type: dns\n                    handler_net_1:\n                        type: net\n            input:\n                input_type: pcap\n                tap: default_pcap\n            kind: collection\n"}
{"level":"info","ts":1640872335.5744474,"caller":"pktvisor/pktvisor.go:230","msg":"pktvisor stdout","log":"[2021-12-30 13:52:15.574] [visor] [error] {\"error\":\"policy with name 'test_policy_name_BrURjEnSAH' already defined\"}"}
{"level":"warn","ts":1640872335.5744832,"caller":"policyMgr/manager.go:142","msg":"policy failed to apply","policy_id":"c3a96ddd-9496-43a6-8924-16a85ddf3314","policy_name":"test_policy_name_BrURjEnSAH","error":"500 policy with name 'test_policy_name_BrURjEnSAH' already defined"}
{"level":"info","ts":1640872390.833336,"caller":"pktvisor/pktvisor.go:230","msg":"pktvisor stdout","log":"[2021-12-30 13:53:10.833] [visor] [info] REQUEST: GET /api/v1/policies/__all/metrics/bucket/1 200"}
{"level":"info","ts":1640872390.8336146,"caller":"pktvisor/pktvisor.go:297","msg":"scraped metrics for policy","policy":"test_policy_name_BrURjEnSAH","policy_id":"c3a96ddd-9496-43a6-8924-16a85ddf3314","payload_size_b":806}

<br>

{
    "id": "c3a96ddd-9496-43a6-8924-16a85ddf3314",
    "name": "test_policy_name_BrURjEnSAH",
    "tags": {},
    "backend": "pktvisor",
    "policy": {
        "handlers": {
            "modules": {
                "handler_dns_1": {
                    "type": "dns"
                },
                "handler_net_1": {
                    "type": "net"
                }
            }
        },
        "input": {
            "input_type": "pcap",
            "tap": "default_pcap"
        },
        "kind": "collection"
    },
    "version": 3
}

**Comment by weyrick** [comment]
I have a feeling we simply never implemented support for updating an existing policy in the pktvisor backend in orb-agent

**Comment by manrodrigues** [comment]
related to #721
