### ISSUE TITLE
Not able to register new account ("REGISTER" button is not working)

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#737]
Button is not sending any request to endpoint users (version -> 0fe8fef3201cc31e7a7da8faed1aecb17a0185e0)

**Comment by gpazuch** [comment]
![clickwrap](https://user-images.githubusercontent.com/1490938/148773785-3a68d63f-3916-411b-8d68-cbc3aa21585e.gif)

**Comment by manrodrigues** [comment]
@gpazuch  Two comments about things that I noticed.
1) one that I can see in your gif as well, that is, even when user can register an account, a token error is displayed. If token is alright, this error must not appear, but if there is a problem with token, user must not be enabled to register an account.
<br>

![image](https://user-images.githubusercontent.com/78241475/148985193-1e9b302f-347d-43b0-b484-034371a1b11a.png)

<br>


![register_account2](https://user-images.githubusercontent.com/78241475/148985901-59e8973a-eb36-4280-a418-92dbb80a774a.gif)

2)if user forget to click on acceptance term, help message is correctly displayed, but user is not enable do register account anymore, because register button keeps disabled

<br>

![register_account](https://user-images.githubusercontent.com/78241475/148986148-1464d1b5-6b2a-4f85-8d10-8098939500e4.gif)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/149349527-5a03c19e-54e8-4c85-85c6-fcdfa27575f2.png)

It seems I'm always getting an error response on register endpoint, it seems to expect a token from the register endpoint as well as the authenticate endpoint.

I'm looking for a fix
