### ISSUE TITLE
Show policy / dataset and status list on agent view page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#763]
As a user, I would like to know which policies and datasets (and their status) are operating on my agent so I can have a quick view if there is something wrong with them.

--

**Section (highlighted):**
![image](https://user-images.githubusercontent.com/86745196/152771615-010e2482-ac0c-438d-b820-120ab04090dd.png)

**FR001**: It should list every policy and dataset (tree view) operating on the agent. The list should be gotten from the Agent API.

**FR002**: It must be possible to collapse each policy by showing or hiding each dataset attached to it. (see screenshot above).

**FR003**: Despite the screenshot above, we should show the Dataset name instead of its ID. That name should be gotten from Dataset API.

**FR004**: Each policy should have its current status right after its name. The status should be gotten from Agent API and the policy name from the Policy API.

**FR005**: If the status mention **ERROR**, when collapsing the policy, it should show the **Error Details** (message) along with the datasets.

**FR006**: If the agent does not have any policy attached to it, you should show a message to the user: "You don't have any policy attached to this agent yet but you can create one by clicking **_here_**"

**_Notes:_** Section **Full View** action should be ignored for now.

--

AC:

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**AND** the agent has no policy attached to it
**THEN** it should see the **Active Policies / Datasets** section with the message "You don't have any policy attached to this agent yet but you can create one by clicking **_here_**"

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**AND** the agent has at least one policy attached to it
**THEN** it should see the **Active Policies / Datasets** section

**GIVEN** user access a specific agent view page
**WHEN** the agent has at least one policy attached to it
**AND** user check the  **Active Policies / Datasets** section
**THEN** it should see the list of policy and datasets set with its current status

**Comment by iatdaitan** [comment]
@gpazuch could you please check this updated issue and estimate it again?

**Comment by gpazuch** [comment]
@iatdaitan There is a field containing each policy name on agent response payload, but it is empty - alternatively, I can query policy names and filtering by id.

![image](https://user-images.githubusercontent.com/1490938/153299776-20b2158a-9be7-40ab-9a79-cc7fc1d3aae4.png)


```
{"id":"e3a87773-4d63-477d-9cd7-182ac99799f2","name":"test_agent","channel_id":"3462fdc6-1c91-4101-8183-e52b024d0336","agent_tags":{},"orb_tags":{"test":"true"},"ts_created":"2022-02-09T15:21:18.620704Z","agent_metadata":{"backends":{"pktvisor":{"data":{"taps":{"default_pcap":{"config":{"iface":"enp0s31f6"},"input_type":"pcap","interface":"visor.module.input/1.0"}}},"version":"4.1.0-develop-1309a90"}},"orb_agent":{"version":"0.12.0-develop"}},"state":"online","last_hb_data":{"backend_state":{"pktvisor":{"state":"running"}},"group_state":null,"policy_state":{"1f551c00-b4ec-473b-8361-cd57ac46d76a":{"datasets":["8936ccf4-9baf-4db0-a5a5-531b913545db"],"name":"","state":"running"},"5c05b8d0-d247-4b40-bba9-727701d3ce11":{"datasets":["0d4bd1d5-c592-4ee3-8982-2fc7ecc5db90","8373fe61-6259-45e5-b079-8536815853aa","c0a42366-22dd-4ee2-baa1-35b5b4cab6d1"],"name":"","state":"running"}}},"ts_last_hb":"2022-02-09T22:16:06.137423Z"}
```
