### ISSUE TITLE
Register: UI must treat conflict error when user try to register an email already registered on orb

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#768]
API returns correct error (conflict) when user try to register an already registered email, but UI have no span or soft way to fail on these situations. It's necessary to display some mensagem like: "this email is already registered"

[Edited]: I'm inserting this new information:
- Even when email is already registered, if I try to register again, the ironclad email is sent confirming registration

**Comment by gpazuch** [comment]
related to issue #778

**Comment by manrodrigues** [comment]
@gpazuch  Any error message is being displayed:

![not_working_register](https://user-images.githubusercontent.com/78241475/171855144-b9aa96e1-da34-433b-ba9d-860504611eb8.gif)

**Comment by gpazuch** [comment]
https://github.com/ns1labs/orb/pull/1378

unable to connect PR due to existing links

**Comment by manrodrigues** [comment]
ok

![error_conflict](https://user-images.githubusercontent.com/78241475/176450648-e56b8b2e-93bf-44b2-9da0-3581861db918.gif)
