### ISSUE TITLE
orb-agent: implement graceful pktvisor restart on failure

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#771]
`func (p *pktvisorBackend) checkAlive() (bool, error)` is called on heartbeat and before interacting with pktvisor API. Although it can detect when pktvisor fails, it currently does not restart the process. This means the orb-agent gets into an invalid state when pktvisor fails/segfaults. The goal of this ticket is implement a graceful restart of pktvisor when it fails.

We should have a way to notify Orb control plane when a failure occurs - perhaps this is just GetState() which return status during heartbeat.
--

Note: add the error log array to the backend response json to hold the last five errors.

**Comment by iatdaitan** [comment]
Its related to #210

**Comment by weyrick** [comment]
the related may fix #1033
