### ISSUE TITLE
Register: token fails and register button doesn't re-enable

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#778]
@gpazuch  Two comments about things that I noticed.
1) one that I can see in your gif as well, that is, even when user can register an account, a token error is displayed. If token is alright, this error must not appear, but if there is a problem with token, user must not be enabled to register an account.
<br>

![image](https://user-images.githubusercontent.com/78241475/148985193-1e9b302f-347d-43b0-b484-034371a1b11a.png)

<br>

![register_account2](https://user-images.githubusercontent.com/78241475/148985901-59e8973a-eb36-4280-a418-92dbb80a774a.gif)

2)if user forget to click on acceptance term, help message is correctly displayed, but user is not enable do register account anymore, because register button keeps disabled

<br>

![register_account](https://user-images.githubusercontent.com/78241475/148986148-1464d1b5-6b2a-4f85-8d10-8098939500e4.gif)

**Comment by manrodrigues** [comment]
i'm just moving the issues to this card, once now we are able to register an account, so, i'm closing #737

**Comment by gpazuch** [comment]
@iatdaitan p1 maybe?

**Comment by iatdaitan** [comment]
@gpazuch For now, guess it is a p2. Let's deal with it after some important issues and polishments.

**Comment by manrodrigues** [comment]
@gpazuch I guess it's ok... i'd like that the buttom only enables when the terms are marked.. but.. not seems to be a problem this way.

![buttom_register_enabled](https://user-images.githubusercontent.com/78241475/171855287-69e628b8-2c20-4eba-b9e0-51d1502ba914.gif)

**Comment by gpazuch** [comment]
@manrodrigues oops
