### ISSUE TITLE
sinker fixes to track pktvisor "name" label in top K metrics

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#779]
Followup from pktvisor ns1labs/pktvisor#158:

We need to add the same logic here https://github.com/ns1labs/orb/blob/a61cfc2b317439ce55e61dd4bc99576c642a6abb/sinker/backend/pktvisor/pktvisor.go#L121 which we added in https://github.com/ns1labs/pktvisor/pull/183/files

The goal is to transition the "name" label on Top N metrics to something more domain specific. We will need to map the metric name to the new Top N specific label (per the pktvisor patch), and rewrite it in real time in the sinker pktvisor backend.

**In addition,** there is a minor pktvisor/orb labeling difference in percentiles. pktvisor does not use a trailing zero on the percentiles:
```
packets_rates_pps_total{instance="gw",quantile="0.5"} 23
packets_rates_pps_total{instance="gw",quantile="0.9"} 115
packets_rates_pps_total{instance="gw",quantile="0.95"} 159
packets_rates_pps_total{instance="gw",quantile="0.99"} 281
```
Orb is currently adding the trailing zeros to "0.5" and "0.9" which is breaking dashboards:
```
dns_rates_total{agent="blesk", agent_id="c2e893e7-1353-46e7-8ce1-82d4ec5e242f", instance="blesk", policy="third", policy_id="1f314929-6677-461c-b6ea-c9c3230ad4ce", quantile="0.50"}
dns_rates_total{agent="blesk", agent_id="c2e893e7-1353-46e7-8ce1-82d4ec5e242f", instance="blesk", policy="third", policy_id="1f314929-6677-461c-b6ea-c9c3230ad4ce", quantile="0.90"}
dns_rates_total{agent="blesk", agent_id="c2e893e7-1353-46e7-8ce1-82d4ec5e242f", instance="blesk", policy="third", policy_id="1f314929-6677-461c-b6ea-c9c3230ad4ce", quantile="0.95"}
dns_rates_total{agent="blesk", agent_id="c2e893e7-1353-46e7-8ce1-82d4ec5e242f", instance="blesk", policy="third", policy_id="1f314929-6677-461c-b6ea-c9c3230ad4ce", quantile="0.99"}
```
see https://github.com/ns1labs/orb/blob/a61cfc2b317439ce55e61dd4bc99576c642a6abb/sinker/backend/pktvisor/pktvisor.go#L140

```

**Comment by manrodrigues** [comment]
![image](https://user-images.githubusercontent.com/78241475/151846913-1677e854-f22b-44c2-9245-ca6b9968c619.png)

![image](https://user-images.githubusercontent.com/78241475/151847005-299a7cfd-fed9-4cc6-b53d-6866520d64d1.png)
