### ISSUE TITLE
Policy editing is not stable

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#793]
After update orb-agent i'm not enable to edit a policy anymore.

Using the agent provisioned with old version I was able to edit, but using agent provisioned with last version, editing is not enabled.

- I tried on localhost and the behavior is the same
- I removed the old agent and provisioned another one using new orb-agent (using `tester@email.com` account) and editing of the same policies that were working before, is not working anymore

![edit_policies](https://user-images.githubusercontent.com/78241475/151004426-7b7582ba-bdfd-4b7a-92a4-43c07b5d1e30.gif)

**Comment by gpazuch** [comment]
I'll need to debug this scenario to find out what is happening.

When talking about versions, @manrodrigues , you mean versions of the orb-agent or the orb-ui?

**Comment by manrodrigues** [comment]
Localhost:
Editing not working:

```
{"id":"6b0a07ff-4721-4ae0-8caf-d4648b415471","name":"policy-localhost-error","tags":{},"backend":"pktvisor","schema_version":"1.0","policy":{"handlers":{"modules":{"handler_dns_1":{"filter":{},"type":"dns"}}},"input":{"input_type":"pcap","tap":"default_pcap"},"kind":"collection"},"ts_last_modified":"0001-01-01T00:00:00Z"}
```

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/153260243-eba10d0b-1e02-49bf-9aa1-029580a322b8.png)

```
{"level":"info","ts":1644429158.613835,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-09 17:52:38.613] [visor] [info] REQUEST: POST /api/v1/policies 200"}
{"level":"info","ts":1644429158.6139433,"caller":"policyMgr/manager.go:175","msg":"policy applied successfully","policy_id":"7d0ad672-8c51-417b-85f9-7f7849a7e46f","policy_name":"policy-dns"}
```
