### ISSUE TITLE
When a policy failed to apply, UI must notify it

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#807]
When a dataset is applied to a group and the policy fails to apply, UI must notify it to the user.. for now, is impossible, just using ORB site, to know if policy was successfully applied or not.

Policy fails:

![image](https://user-images.githubusercontent.com/78241475/151443987-52202699-4f00-4935-acb6-1c48406e576f.png)

And dataset is valid with no notification:

![image](https://user-images.githubusercontent.com/78241475/151443843-921dcd72-c196-41b3-84cf-120ba436faab.png)

**Comment by iatdaitan** [comment]
@weyrick is agent view enhancement enough to address this issue or should we think more about it?

**Comment by weyrick** [comment]
@iatdaitan yes this will be solved by agent view enhancement

**Comment by manrodrigues** [comment]
@iatdaitan @weyrick  Since the function of the dataset is to apply the policy on a certain group, shouldn't there be a way in the dataset of this being notified? shouldn't the dataset be invalidated if the policy fails? thinking about a group with many agents, maybe it makes sense to have a more macro view of the error than looking at each agent.. what do you think?

**Comment by weyrick** [comment]
@manrodrigues you are right that it would be great to get a view of failures from the dataset as well - or enhanced policy view, since I think we want to move datasets inside of policies. let's work on that when we designed the policy view page. a dataset should never be invalidated when it fails to apply to an agent though. datasets are only invalid when its policy, group, or sink is removed.

**Comment by manrodrigues** [comment]
Got it.. Good to know.. Thank you.

**Comment by manrodrigues** [comment]
once we will work on that when we design the policy view page, i'm gonna remove the p1 label

**Comment by manrodrigues** [comment]
@iatdaitan i think we can close this, once agent's view show the policies status now. What do you think?

**Comment by gpazuch** [comment]
@acarvalhal moving this to icebox for revision

**Comment by acarvalhal** [comment]
Evaluate whether the UI should show a notification informing whether the policy was applied correctly or not to all agents. Something like: "Policy applied to all agents" or "Policy not applied to one or more agents"

**Comment by manrodrigues** [comment]
Outdated

![image](https://user-images.githubusercontent.com/78241475/180453892-24db30ad-ed18-4656-b9c1-92b027f284ff.png)
