### ISSUE TITLE
Add handler step UX improvement

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#812]
Add handler step is confusing and user and we need to improve the user experience there.
The idea is to have a message, telling the user this is a required step and we should have at least one handler.
Bellow that we should have a button "New Handler"

Upon click, we should show a modal to the user, allowing them to follow the actual view we have to create handlers.
The modal should have the following buttons: Cancel, Add and continue and Add and close

After the user adds a new handle, it should show on the parent page/step the added handler.

The primary save/next button should be disabled until we have at least one handler.

Note: We should not allow/show to the user the handler name input.

**Comment by manrodrigues** [comment]
Modal ok
![policy_modal](https://user-images.githubusercontent.com/78241475/153247442-ca8310cf-327d-4279-b319-07d665edc9b8.gif)
