### ISSUE TITLE
Implement logic (AND/OR) for tags

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#827]
Implement functionality that allows users to use logic AND /OR on tags:

e.g.: 
- tag 1 AND tag 2 OR tag 3

**Comment by gpazuch** [comment]
@iatdaitan should this card be split into two? [frontend, backend]

**Comment by gpazuch** [comment]
https://gist.github.com/gpazuch/d2befd1b112a10f98e0512c9e1e2641d

**Comment by weyrick** [comment]
this needs backend design and implementation, I recommend we close for now and reopen when this is a priority.
