### ISSUE TITLE
Make current agent information display more compact

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#836]
As a user, I would like to have a more compact view of the agent view page so I should be able to check more information at once without using the scrollbar.

--

**Screenshot (highlighted)**:
![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/034a402d-004d-40dd-a8fb-769cbeb3c0f5)

**FR001:** The UI of the agent information section should be refreshed as shown above. It should hold either the agent information itself (Agent Name, Version, Agent ID, and Channel ID) plus the Agent Tags.

**FR002:** Despite what is shown in the above screenshot, the chips of the Agent Tags should follow the current color design.

**Note:** 
- Provisioning Command should be removed from this section to a separated section - to be addressed in another issue.
- The section's action (Manage button) should be ignored for now.

--

**AC:**

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**THEN** it should see the **Active Information** section

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**THEN** it should follow the UI Spec and Requisites mentioned in this page

**Comment by iatdaitan** [comment]
1st task from #676

**Comment by iatdaitan** [comment]
@gpazuch could you please analyze and estimate this issue?

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/155651988-b5142f67-35fe-4453-9d00-34371bd3f0f2.png)

![image](https://user-images.githubusercontent.com/78241475/155652067-9d72600e-a4e7-45cb-8f3f-41efef82f99b.png)
