### ISSUE TITLE
Add provisioning command for each operational system available

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#840]
As a user, I would like to check the respective provisioning command for each available OS so it will allow me to easily run my agent at the edge.

--

**Screenshots:**

Before provisioning the agent:
![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/71703318-7ea7-4b89-b395-a5c7d618ed77)

If Orb had contact with the agent:
![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/814488b6-57d0-4f14-b0f5-de2b31f4131e)

**FR001**: Agent Provisioning Command should have its own separated section as it shows above.

**FR002**: Once the agent has been provisioned the section should be collapsed to save space on the UI.

**FR003**: The section header should also hold a select box to allow the user to choose the OS they desire. After we change the OS target, the provisioning command should change accordingly.

**FR004**: Current copy function shouldn't be affected by this change. Once the user clicks on the copy icon, it should copy to the clipboard the command for the selected OS.

**Note**: As we don't have the current list of all supported OS and its commands, just show a **Docker option** until there. A new issue may be created to address this problem later.

**Technical note:** We may use an object to hold OS, Steps, and Commands for this section. Allowing the UI to mount the steps automatically.

--

**AC**:

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**AND** the agent status is new (not provisioned yet)
**THEN** it should see the **Provisioning Command** section opened with the default command to provisioning the agent

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**AND** the agent has been provisioned before
**THEN** it should see the **Provisioning Command** section collapsed

**GIVEN** user access a specific agent view page
**WHEN** user checks the UI
**AND** go to **Provisioning Command** section
**AND** clicks on the copy command icon
**THEN** the icon should change to a check icon
**AND** the clipboard should be holding the copied command

**Comment by iatdaitan** [comment]
2nd task from #676

**Comment by iatdaitan** [comment]
@gpazuch could you please analyze and estimate this issue?

**Comment by manrodrigues** [comment]
![prov_com](https://user-images.githubusercontent.com/78241475/155652486-a322c339-7a4b-477f-a3c5-57aa74eb5945.gif)
