### ISSUE TITLE
Grafana dashboard must display only policies applied to selected agents (filter option)

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#860]
On grafana's dashboard, only policies applied to the selected agents must be displayed as filter option (nowadays, all policies are being listed)

![image](https://user-images.githubusercontent.com/78241475/153488583-b1beb7d6-4c66-41f3-b1b5-2c616becd4d5.png)

**Comment by iatdaitan** [comment]
@weyrick is taking care of the dashboard improvements.
