### ISSUE TITLE
Dataset view: Implement column to list display to which group the dataset linked

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#862]
Once now user is obligated to open each dataset in order to know to which group and policy each dataset is linked, our intention here is to develop a way to show this important information  on dataset's page.

Nowaday:

![image](https://user-images.githubusercontent.com/78241475/153489993-8fb05b48-04e7-4583-bc76-8379d15271ba.png)

**Comment by iatdaitan** [comment]
@weyrick lets refine it a little bit more and discuss with @eremmele about a better solution for this page.

**Comment by gpazuch** [comment]
@iatdaitan 
@acarvalhal 
Closing this issue - obsolete/unused.
