### ISSUE TITLE
Ability to duplicate an existing Policy

### ISSUE THREAD

**Issue by weyrick** [ns1labs/orb#885]
As an Orb user, I want the ability to easily duplicate an existing Policy so that I can create a similar Policy with small changes, without affecting existing uses of that Policy in my existing Agents.

**Comment by manrodrigues** [comment]
ok. Last commit - https://github.com/ns1labs/orb/commit/816b9f8be94ec1ef2f1ee6b242cc0f691b525f85


![policy_duplicated](https://user-images.githubusercontent.com/78241475/167678502-5c1d6eab-2232-4860-95fa-1378370bfe82.gif)
