### ISSUE TITLE
Agents: provision command must work by copying pasting directly from page

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#890]
Provisioning command displayed on agent's view page must be the same as one get by clicking the clipboard icon (we need to remove break lines and insert "\\" at the end of each line.

# Current: <br>
<br>

```
docker run -d --net=host

-e ORB_CLOUD_ADDRESS=stage.orb.live

-e ORB_CLOUD_MQTT_ID=d8fe01ac-9bc7-4cd1-b561-f15bfe1d9051

-e ORB_CLOUD_MQTT_CHANNEL_ID=03ada49f-839d-44d9-bdce-e8fa0cd3360a

-e ORB_CLOUD_MQTT_KEY=undefined

-e PKTVISOR_PCAP_IFACE_DEFAULT=mock


ns1labs/orb-agent:develop

```

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/21b79061-276e-4eab-b844-0962bba458f8)

# Expected: <br>
<br>

```
docker run -d --net=host \
-e ORB_CLOUD_ADDRESS=stage.orb.live \
-e ORB_CLOUD_MQTT_ID=d8fe01ac-9bc7-4cd1-b561-f15bfe1d9051 \
-e ORB_CLOUD_MQTT_CHANNEL_ID=03ada49f-839d-44d9-bdce-e8fa0cd3360a \
-e ORB_CLOUD_MQTT_KEY=undefined \
-e PKTVISOR_PCAP_IFACE_DEFAULT=mock \
ns1labs/orb-agent:develop
```

**Comment by gpazuch** [comment]
```
docker run -d --net=host \
-e ORB_CLOUD_ADDRESS=localhost \
-e ORB_CLOUD_MQTT_ID=ac136c61-4914-4691-b352-decb1a5bcc8c \
-e ORB_CLOUD_MQTT_CHANNEL_ID=e455ca62-5427-4509-8425-cbe400018da4 \
-e ORB_CLOUD_MQTT_KEY="PASTE_AGENT_KEY" \
-e PKTVISOR_PCAP_IFACE_DEFAULT=mock \
ns1labs/orb-agent:develop

```
that seems to be the case.

![image](https://user-images.githubusercontent.com/1490938/156422769-4604f3be-6eb9-4dc4-ac41-a691b16eea0e.png)

**Comment by gpazuch** [comment]
@manrodrigues you mean the text rendered on the page should show the backslash character `\`?
Should I change that on the agent provisioning page right after the agent is created, too?

**Comment by manrodrigues** [comment]
Command on agent creation is working fine, but on agent's view command have an extra blank line:

![command_paste](https://user-images.githubusercontent.com/78241475/156831774-b2dd4376-1f9f-405b-8b17-ff59dd8359e7.gif)

**Comment by manrodrigues** [comment]
Action needed: fix behavior of command on agent's view

**Comment by manrodrigues** [comment]
![paste_command_ok](https://user-images.githubusercontent.com/78241475/156854234-bdd2c062-39f3-4060-b4e5-f0a59fd317bc.gif)

ok
