### ISSUE TITLE
Agents: provision command on agent's view must have help message in order to instruct user to change necessary fields

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#901]
We need to insert help message. Help message must instruct the user to change the red fields

Second thing: I, personally, think that once `{{}}` symbol is only present for agent key, it may confuse users that can try to pass command putting the key between the symbols

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/1529ae9f-be69-44ee-b929-8b1eada99003)

**Comment by gpazuch** [comment]
@iatdaitan It's a bit unclear.

**Comment by iatdaitan** [comment]
Yes, please remove the brackets and replace the space with an underscore. So it should look like this: **AGENT_KEY**

For the message, we may use the bellow:
"You must include an Agent key before using the provisioning command. In the following command, please replace **AGENT_KEY** with your Agent key.

If you are looking for scrapping real data from your Agent, please consider changing the **mock** with your Agent default iface."

**Comment by weyrick** [comment]
To use the provisioning command, you must replace AGENT_KEY with the Agent Key given to you during agent creation. If you have lost the Agent Key, you must remove and create a new agent.

**Comment by manrodrigues** [comment]
ok

last commit: https://github.com/ns1labs/orb/commit/26cace42fd39535432cf29d4420b5ac207640c2d

![image](https://user-images.githubusercontent.com/78241475/159490679-d16acd35-41dc-49a5-bf67-bfb2d161b057.png)

**Comment by manrodrigues** [comment]
@gpazuch  But now this help message is also being displayed on agent credentials modal, where is not right/necessary once we don't need to replace the key and we already have an information to change iface.

**Comment by manrodrigues** [comment]
ok

last commit - https://github.com/ns1labs/orb/commit/cb5e029acf46db722b2291719c0695b548a98b6f



![image](https://user-images.githubusercontent.com/78241475/159710833-7d3ff3ad-eb12-4d35-b96e-2bb9d046ea5a.png)


![image](https://user-images.githubusercontent.com/78241475/159711250-b1afb722-55a7-4515-b79a-b888897893c8.png)
