### ISSUE TITLE
Agent groups: implement responsive design to matching agents table

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#903]
Using bigger screens, table of matching agents is correctly displayed:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/45fcdd63-896a-4f00-887c-142f519ed345)

but using smaller ones, table is poorly distributed:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/a64e9e3f-728c-47c0-9101-a92f8bd3a958)

Expected result: table must autoadapt the size and distribution to keep correctly displayed even in smaller screens

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/166500155-c958cb5a-00a5-41db-813b-2c2295e18727.png)
I haven't yet applied responsiveness to those tables in Orb.

I have adjusted the columns for now.
