### ISSUE TITLE
Sinks: delete button is misplaced on sinks page

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#936]
Note that you can barely see the button

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/3790f443-5356-4d7d-b776-f987eb542862)

**Comment by gpazuch** [comment]
@manrodrigues can you check this again if your browser zoom is set to 100%?
![image.png](https://images.zenhubusercontent.com/61a8d9664f6f702d670d050e/834b0ba7-4a53-4b72-9905-b05b7ad9e716)
this looks odd. nevertheless I'll try and fix this issue for datatables soon

**Comment by lpegoraro** [comment]
Moved since it was fixed in a different PR

**Comment by manrodrigues** [comment]
ok
