### ISSUE TITLE
Agents view: groups matching are not being displayed on agent's view before dataset

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#946]
If one agent has groups that match with this agent, these groups must be displayed on agent's view, even if no dataset is applied to the the group/agent.

Note that there is an group that matches with this agent, but this group is not being displayed on agent's view:

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/51b12f09-3c71-4747-ac74-28480269ce0f)

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/44b514d7-4d93-4b79-951e-d2fea7fce79a)

![image.png](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/04032670-ffcd-4f64-8660-f1011fb3a7cd)

**Comment by gpazuch** [comment]
@iatdaitan I'm not sure what to do with this issue for the FrontEnd except the warning text saying the groups and datasets can only be retrieve once its been applied to a dataset

**Comment by dscabral** [comment]
@gpazuch I'm going to create a way to return the matching groups... I'll let you know when ready.

**Comment by dscabral** [comment]
I'm thinking of creating a new field called `matching_groups` with this content 
```
[
  {
    "group_id": "a01bbf4f-d40b-442a-8141-ff5006bcc230",
    "name": "group-2",
    "channel": "bed427b6-4433-4f45-85db-9a0e071bff24"
  },
  {
    "group_id": "aae1481a-4c71-4ebd-8580-524de48f8061",
    "name": "agent-3",
    "channel": "c229216e-e4ec-44c3-b63b-e46f28c6666f"
  }
]
```
Is it acceptable?

**Comment by gpazuch** [comment]
@dscabral 

So the issue being that `last_hb_data` is not present when retrieving a newly created agent, we need a way of retrieving which groups is this agent part of, and which policies, if any, should be applied to it when it becomes online.

Perhaps `matching_groups` could be nested inside `agent_metadata`, but it makes little difference I guess - as well as field for the policies, too;

Group name and channel are handy as of now, but my concern is that I should not depend on it, but rather retrieve the corresponding ID from the group services - it seems a tad more future proof.

**Comment by manrodrigues** [comment]
ok

![group_before_dataset](https://user-images.githubusercontent.com/78241475/162353193-1c391eb4-aae4-442d-bd96-88f1983eeda5.gif)
