### ISSUE TITLE
Datasets: the invalid dataset doesn't became valid after editing

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#950]
When the dataset became invalid  for not having linked sinks, if I edit the dataset and include a valid sink, dataset status must be valid again and must reapply to the agent.

Steps to reproduce:

1 - Apply a policy to an agent
2 - Remove all the sinks linked on the dataset
3 - Create a new valid sink
4 - Edit the dataset inserting the sink

Expected result:

- Dataset must be with "valid" status
- Dataset must be reapplied to the agent

![dataset_invalid_after_sink.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/93a2a7bd-562d-4198-abde-e5887ac2eb87)

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/161832128-0379493f-ac16-4232-a75f-baa37a4716ee.png)

![image](https://user-images.githubusercontent.com/78241475/161832226-874d0d15-735f-4117-bf89-325c365be401.png)

**Comment by manrodrigues** [comment]
i'm reopening this issue because I was testing a bit more.. and notice that, although the dataset became active after editing, the dataset is not reapplied to the agent. What we expected is that the dataset is reapplied to the agent. 

teps to reproduce:

1 - Apply a policy to an agent
2 - Remove all the sinks linked on the dataset
3 - Create a new valid sink
4 - Edit the dataset inserting the sink

Expected result:

Dataset must be with "valid" status
**Dataset must be reapplied to the agent**
- check agent's view page and agent heartbeats.. datasets and policies related to the edited dataset must be reapplied to the agent

**Comment by manrodrigues** [comment]
its ok:

![image](https://user-images.githubusercontent.com/78241475/162036915-c32ec660-feb6-43be-a9f7-97f4a7c3d24d.png)

**Comment by lpegoraro** [comment]
relates to #1088

**Comment by manrodrigues** [comment]
Ok!

![policy_after_dataset_Active](https://user-images.githubusercontent.com/78241475/177177980-37f00bf8-4d68-44a6-85eb-c0594ab959bc.gif)
