### ISSUE TITLE
Agents: insert a way to reset agent through the UI

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#956]
Once #520 and #899 is done, we could insert a way to reset the agent through the UI (using a button on agent's view page?)

So, if something turn broke the agent or if something fail, the user can try to reset the agent.

**Comment by manrodrigues** [comment]
@gpazuch 

Steps:

POST request on endpoint `/agents/:id/rpc/reset`

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/162024323-4c2e3caf-6f44-4604-aa3d-5f668a1ff032.png)

**Comment by manrodrigues** [comment]
ok

![image](https://user-images.githubusercontent.com/78241475/162352338-8a3a41a3-0fac-4420-94e8-5b1790dcd15d.png)


![reset_agent](https://user-images.githubusercontent.com/78241475/162352918-76f62fe3-eab6-41ba-a11c-9e943b22b7d7.gif)
