### ISSUE TITLE
Agents: agent's view page is not being displayed for new agents

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#964]
When a new agent is created, the agent view's page is not being displayed. So, the user is not enabled to get the provision command to run the agent.

Steps to reproduce:
- Create an agent without provision
- Open the agent's view page

Expected result:
- Page must have agents information and the provision command

Current result:
- Agent's view page is empty

![withou_view.gif](https://images.zenhubusercontent.com/61aa14a937730b887dff82b3/82014fc2-1ad9-44ac-8a4f-f661b5551182)

**Comment by manrodrigues** [comment]
@gpazuch  For new agents the buttons are still broken and there is no provision command 

![image](https://user-images.githubusercontent.com/78241475/159723564-c056de02-5371-489d-8db9-aa7d3da6b00b.png)

**Comment by gpazuch** [comment]
@manrodrigues alright, thx. that's odd, I'm going to verify this real quick.

**Comment by gpazuch** [comment]
@dscabral @iatdaitan 
if user retrieves agent instants after it's been created, service response is

![image.png](https://images.zenhubusercontent.com/61a8d9664f6f702d670d050e/25ad2c3d-5199-4b55-a8a2-0acf8782d7f1)


I should improve the page to be more resilient of fragmented data, but it is missing it's agent metadata field.

**Comment by manrodrigues** [comment]
ok

last commit - https://github.com/ns1labs/orb/commit/5edfd8a64464a8a83b023e6f2ed623073f79cc9f

![image](https://user-images.githubusercontent.com/78241475/159980141-5fe5de02-1a25-4095-8042-7a2faa592d0c.png)
