### ISSUE TITLE
Add Agent Groups section to Policy View page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#985]
As a user, I would like to check with agent groups that are using specific Agent Groups and which agents are matched by each group so I can fastly check which agents are being affected by the current policy without having to change to another page.

--

**Screenshot (WIP)**: 
![image.png](https://images.zenhubusercontent.com/618e6c9ac4cdae7c608415f6/9a7449ae-b111-45a3-911e-7e63e6cb2b60)

**FR001**: The section should use "Active Groups" as its heading.

**FR002**: It should list each Agent Group that is using the active policy.

**FR003**: Each Agent Groups name should be clickable and once clicked it should show a modal to the user with all the agents that are included in that specific group.

**Comment by manrodrigues** [comment]
@gpazuch when the user click on the group name, we should display the agents matching, right? Not the details of the group.

```
FR003: Each Agent Groups name should be clickable and once clicked it should show a modal to the user with all the agents that are included in that specific group.
```

**Comment by manrodrigues** [comment]
@gpazuch @acarvalhal I confirmed this right now on localhost and the group section seems to not be working anymore (doesn't exist on policies view page).. so its not a deploy config problem.. we need to check on development what happened. 
![image](https://user-images.githubusercontent.com/78241475/164517874-9def4de1-9c5f-4110-ad1a-4d80327fca77.png)


![image](https://user-images.githubusercontent.com/78241475/164517637-c65d1015-037f-4f2b-ad3a-57389fe6ba9a.png)

**Comment by gpazuch** [comment]
related to pr #1069

**Comment by manrodrigues** [comment]
> @gpazuch when the user click on the group name, we should display the agents matching, right? Not the details of the group.
> 
> ```
> FR003: Each Agent Groups name should be clickable and once clicked it should show a modal to the user with all the agents that are included in that specific group.
> ```

Now we have the section.. so.. i'm asking again.

what we have now is this:

![image](https://user-images.githubusercontent.com/78241475/164599843-542a78c2-41e1-4318-9206-26626d85591b.png)


but we expected the matching agents, right?
