### ISSUE TITLE
Editing Handlers on Policy View Page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#986]
As a user, I would like to be able to edit handler information (create, updated, and delete) on the Policy View page so I do not have to use the whole form to edit specific information.

--

**Screenshot**:  TBD

**FR001**: Each handler listed on the Agent Policy Details section must be clickable. Upon click, it should show the user the same modal used during the policy creation using the Wizard with the current information of the clicked handler.

**FR002**: During the handler editing feature, the modal should have a new button called "Delete", to allow the user to delete the current handler. Note: The user can't delete all available handlers. By trying to delete the last handler a message should be shown to the user informing why that action can't be performed.

**FR003**: A button called "Add new handler." should be placed right after the list of Handlers. Once clicked the same modal used during the policy creation using the Wizard should be shown to the user allowing a new handler creation to that specific policy. After being created and persisted it should be shown between the last existing handler and the "Add new handler" button.

**Comment by gpazuch** [comment]
https://www.npmjs.com/package/yaml-validator

@leoparente  
do we have some sort of schema for pktvisor yaml validation?

**Comment by leoparente** [comment]
> https://www.npmjs.com/package/yaml-validator
> 
> @leoparente do we have some sort of schema for pktvisor yaml validation?

We do the validation for our fields manually. we dont have this pretty schama.
you can find our logic here:
https://github.com/ns1labs/pktvisor/blob/develop/src/Policies.cpp

**Comment by manrodrigues** [comment]
@gpazuch  I'm not able to test this functionality.. can you check if the correct code is merged, please? If yes, please confirm with @etaques if the build was successfully done.

![not_able](https://user-images.githubusercontent.com/78241475/166707910-1908ff6a-fc42-4cd2-ac8b-3ca059b63b51.gif)

**Comment by manrodrigues** [comment]
ok - last commit - https://github.com/ns1labs/orb/commit/b0b9af0cfe3a60c1ebad6d55f702bcfcc7cfa2b4

![policy_editing_with_view_page](https://user-images.githubusercontent.com/78241475/167181919-952a0c28-61e5-4b27-8769-06fc9e9892a1.gif)
