### ISSUE TITLE
Active Dataset list on Policy View page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#987]
As a user, I would like to check the dataset list of a specific Policy on the Policy view page, allowing me to easily identify what are the available dataset and which group and sinks are being used on it.

--

Figma: 
https://www.figma.com/file/5jZNpc8JMsY2Tj3OQJzgxt/Orb-Product-Portal-UI?node-id=2419%3A16591

Screenshot:
![image](https://user-images.githubusercontent.com/86745196/162468345-2f79efad-81cb-4561-86d2-3a389b28470e.png)

FR001: The list should show the Dataset name, Agent Group used, and list all the sinks of the dataset.
FR002: Once the user clicks on the Agent Group name, the Agent Match modal should be show listing all the agents of that specific group.

**Comment by gpazuch** [comment]
related to pr #1069

**Comment by manrodrigues** [comment]
```
FR002: Once the user clicks on the Agent Group name, the Agent Match modal should be show listing all the agents of that specific group.
```

@gpazuch  Should the groups being clickable? 

![image](https://user-images.githubusercontent.com/78241475/164603685-a0c78fd9-f90d-4de7-b592-3ccc1175e17c.png)

**Comment by manrodrigues** [comment]
closing based on #1105
