### ISSUE TITLE
Remove Dataset List View page menu to disable/hide Dataset creation and Editing from Dataset list view page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#989]
As a USER, since the Dataset is going to be moved inside of the Policy View page, I would like to remove the Dataset list view route and its menu so I can avoid confusion during the use of the Orb Control Panel.

**Comment by manrodrigues** [comment]
@gpazuch the route for datasets page still exist and the menu link direct the user to it.

![rout_dataset](https://user-images.githubusercontent.com/78241475/164607279-93c885bb-88e5-4167-a790-9d99eafa4c4a.gif)

Another think is that on left menu, considering the logic creation, the sink must be above the policy.. you have changed the order:

![image](https://user-images.githubusercontent.com/78241475/164607507-12f59f47-5eb4-4a26-a4ca-84c7d7fec1dd.png)

**Comment by manrodrigues** [comment]
closing based on #1106 and #1107
