### ISSUE TITLE
Enable Dataset creation from policy view page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#990]
As a User, I would like to be able to create a dataset from the Policy View Page so it will make it easier to direct associate it with a specific policy.

--

General Figma Frame: https://www.figma.com/file/5jZNpc8JMsY2Tj3OQJzgxt/Orb-Product-Portal-UI?node-id=2415%3A14590

Screenshot: 
- List view with new dataset button
![image](https://user-images.githubusercontent.com/86745196/162459331-6fe101c4-b835-428c-8db3-128b4de123db.png)

- Modal after the new dataset button is clicked (Note: the modal is meant for editing a dataset, if it gets confuse, please get in touch with Erica to provide a new design for creating a dataset only.)
![image](https://user-images.githubusercontent.com/86745196/162461304-2f16d218-1b59-4acb-9af2-ada731e95d70.png)

FR001: The Dataset List View inside of the Policy view page should have a New Dataset button to allow the user to click
FR002:  Upon click, a modal should be shown to the user allowing a new dataset to be created.
FR003: The policy field should be disabled and show the current and visible policy.

**Comment by manrodrigues** [comment]
@gpazuch 
1 - policies' view page is crashed when the group or the sink list is expanded/selected.. the same occurs on dataset editing:

![page_bug](https://user-images.githubusercontent.com/78241475/164605792-3e2ecdac-b8de-4e01-8fea-7bfafd5f56b7.gif)

![page_details_bug](https://user-images.githubusercontent.com/78241475/164605820-386299c4-a288-426a-a96c-b0dc2cc38204.gif)

2- only the "name" filter are working for datasets

3- Once that a sink is added, is not possible to remove

![unable_remove_sink](https://user-images.githubusercontent.com/78241475/164606189-f68b8ec4-0c85-4431-bda1-af3e0740b33b.gif)

4 - user is allowed to add multiple times the same sink to the dataset:

![image](https://user-images.githubusercontent.com/78241475/164606317-de20befa-cc86-4089-8647-53588da8bfdc.png)

5 - the modal for create a dataset must not be named as "dataset details", once this is for editing modal:

![image](https://user-images.githubusercontent.com/78241475/164606481-01392c55-a1b6-4492-8961-5aa1ad8f2618.png)

6 - dataset details (after click over the name of an existing dataset) has a "g" above "sinks":

![image](https://user-images.githubusercontent.com/78241475/164606653-1b6fe99a-2e7b-406a-8f8f-127cd1e33315.png)

7 - Button "save" is enabled without required fields on creation and editing modal:

![image](https://user-images.githubusercontent.com/78241475/164606747-3a9122ac-a111-428b-ab8b-15bc44b05b0b.png)

![image](https://user-images.githubusercontent.com/78241475/164606787-9d8c4e88-17fd-4939-a00e-915a36ff4acf.png)

8 - page is not refreshed after create, editing or delete a dataset

9 - mouse icon must be a hand icon when over the dataset name, once it is clickable

10 - of course this is just  a minor, but for maintain the pattern, the name of the button for create a dataset must be 

"+ new dataset", not "+ create dataset"

![image](https://user-images.githubusercontent.com/78241475/164605302-6f369517-18da-4701-99c4-ca430ac79624.png)

And, one question, why we have the amount of datasets displayed into brackets? we don't have this for any other section on orb.

![image](https://user-images.githubusercontent.com/78241475/164606026-871054a2-d18d-4d1f-beb0-1588f2b1382c.png)

**Comment by manrodrigues** [comment]
1 - #1108 
2 - #1109 
3 - #1110 
4 - #1111
5 - #1112 
6 - #1113 
7 - #1114 
8 - #1115 
9 - #1116 
10 - #1117 

Extra - #1118
