### ISSUE TITLE
Enable dataset editing and delete from policy view page

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#991]
As a User, I would like to be able to edit a specific dataset directly from the Policy View Page, make it easier to edit a dataset associated with a specific policy.

--

General Figma Frame: https://www.figma.com/file/5jZNpc8JMsY2Tj3OQJzgxt/Orb-Product-Portal-UI?node-id=2415%3A14590

Screenshot: 
- Dataset List view inside of Policy view page
![image](https://user-images.githubusercontent.com/86745196/162464092-032a359a-4764-45d5-ac88-5575e5209eda.png)

- Modal after the new dataset button is clicked (Note: the modal is meant for editing a dataset, if it gets confuse, please get in touch with Erica to provide a new design for creating a dataset only.)
![image](https://user-images.githubusercontent.com/86745196/162461304-2f16d218-1b59-4acb-9af2-ada731e95d70.png)

FR001: The Dataset List View inside of the Policy view page should allow the user to click on the Dataset Name.
FR002:  Upon click, a modal should be shown to the user allowing the selected dataset to be edited.
FR003: The policy field should be disabled and show the current and visible policy.
FR004: The user should be also able to delete the selected dataset by clicking on the "Delete Dataset" button.

**Comment by manrodrigues** [comment]
Editing a policy is working fine. But:

1 - Note that the page is not being refreshed after editing, so the changes are not automatically displayed:

![edited](https://user-images.githubusercontent.com/78241475/164604596-fbafcbbf-b467-4102-a6b6-ebce867ed3ec.gif)

2 - once that one sink is added, is not possible to remove it. 
3- users are allowed to add multiple times the same sink on the dataset:

![unable_remove_sink](https://user-images.githubusercontent.com/78241475/164604731-469363c1-46c2-4d6c-98e4-55487f8a43b9.gif)

**Comment by manrodrigues** [comment]
closing based on #1119 #1115 #1111 and #1110
